### ISSUE TITLE
Flaky test: OpenTelemetry.AutoInstrumentation.Tests.Diagnostics.SdkSelfDiagnosticsEventListenerTests.EventSourceSetup_LowerSeverity

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#1154]
Found on CI pass for #1153

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/8164049007?check_suite_focus=true#step:5:2379.

```terminal
  Error: [xUnit.net 00:00:01.26]     OpenTelemetry.AutoInstrumentation.Tests.Diagnostics.SdkSelfDiagnosticsEventListenerTests.EventSourceSetup_LowerSeverity [FAIL]
  21:11:44 [ERR] [xUnit.net 00:00:01.26]     OpenTelemetry.AutoInstrumentation.Tests.Diagnostics.SdkSelfDiagnosticsEventListenerTests.EventSourceSetup_LowerSeverity [FAIL]
  21:11:44 [DBG]   Failed OpenTelemetry.AutoInstrumentation.Tests.Diagnostics.SdkSelfDiagnosticsEventListenerTests.EventSourceSetup_LowerSeverity [105 ms]
  21:11:44 [DBG]   Error Message:
  21:11:44 [DBG]    Expected testSink.Messages to be empty because events with lower severity than error should not be written., but found {"[2022-09-02T21:11:44.6411848Z] [Information] EventSource=OpenTelemetry-Sdk, Message=ERROR: Exception in Command Processing for EventSource OpenTelemetry-Sdk: An instance of EventSource with Guid af2d5796-946b-50cb-5f76-166a609afcbb already exists. 
  21:11:44 [DBG] "}.
  21:11:44 [DBG]   Stack Trace:
  21:11:44 [DBG]      at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
  21:11:44 [DBG]    at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
  21:11:44 [DBG]    at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
  21:11:44 [DBG]    at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
  21:11:44 [DBG]    at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
  21:11:44 [DBG]    at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
  21:11:44 [DBG]    at FluentAssertions.Execution.GivenSelector`1.FailWith(String message, Object[] args)
  21:11:44 [DBG]    at FluentAssertions.Collections.GenericCollectionAssertions`3.BeEmpty(String because, Object[] becauseArgs)
  21:11:44 [DBG]    at OpenTelemetry.AutoInstrumentation.Tests.Diagnostics.SdkSelfDiagnosticsEventListenerTests.EventSourceSetup_LowerSeverity() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/OpenTelemetry.AutoInstrumentation.Tests/Diagnostics/SdkSelfDiagnosticsEventListenerTests.cs:line 41
  21:11:44 [DBG] Results File: /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/build_data/results/OpenTelemetry.AutoInstrumentation.Tests/_fv-az198-522_2022-09-02_21_11_44.trx
  21:11:44 [DBG] 
  21:11:44 [DBG] Failed!  - Failed:     1, Passed:    58, Skipped:     0, Total:    59, Duration: 232 ms - /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/OpenTelemetry.AutoInstrumentation.Tests/bin/Release/net6.0/OpenTelemetry.AutoInstrumentation.Tests.dll (net6.0)
```

**Comment by pellared** [comment]
This looks like a bug...

**Comment by pjanotti** [comment]
Another instance https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/8234770095?check_suite_focus=true#step:6:2342
