### ISSUE TITLE
Intermittent IOException from Target CopyAdditionalDeps in local environment

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [open-telemetry/opentelemetry-dotnet-instrumentation#1395]
**CopyAdditionalDeps              Failed          0:09   // IOException: The file 'D:\opentelemetry-dotnet-instrumentation\bin\tracer-home\store\x64\netcoreapp3.1\mongodb.driver.core\2.13.3\runtimes\win\native\libzstd.dll' already exists.**

10:32:39 [ERR] Target CopyAdditionalDeps has thrown an exception
System.IO.IOException: The file 'D:\opentelemetry-dotnet-instrumentation\bin\tracer-home\store\x64\netcoreapp3.1\mongodb.driver.core\2.13.3\runtimes\win\native\libzstd.dll' already exists.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at Build.<get_CopyAdditionalDeps>g__CopyNativeDependenciesToStore|90_4(AbsolutePath file, String depsJsonContent) in D:\opentelemetry-dotnet-instrumentation\build\nuke\Build.Steps.cs:line 429
   at Build.<>c.<get_CopyAdditionalDeps>b__90_3(AbsolutePath file) in D:\opentelemetry-dotnet-instrumentation\build\nuke\Build.Steps.cs:line 382
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
   at Build.<get_CopyAdditionalDeps>b__90_1() in D:\opentelemetry-dotnet-instrumentation\build\nuke\Build.Steps.cs:line 378
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112

**Proposed Fix**
* Add overwrite flag to `File.Copy`

**Comment by Kielek** [comment]
I can fix it tommorw morning, if there will be nor PR.
