### ISSUE TITLE
Fix MySql instrumentation on Ubuntu for MySql 8.0.31

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#1415]
Detected by #1411.

The test issue:

```log
  12:47:46 [DBG]   Failed IntegrationTests.MySqlDataTests.SubmitsTraces [1 m]
  12:47:46 [DBG]   Error Message:
  12:47:46 [DBG]    Expected spans.First().Tags["db.system"] not to be empty.
  12:47:46 [DBG] 
  12:47:46 [DBG]   Stack Trace:
  12:47:46 [DBG]      at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
  12:47:46 [DBG]    at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
  12:47:46 [DBG]    at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)
  12:47:46 [DBG]    at IntegrationTests.MySqlDataTests.SubmitsTraces() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/MySqlDataTests.cs:line 57
  12:47:46 [DBG] --- End of stack trace from previous location where exception was thrown ---
```

**Comment by Kielek** [comment]
Breaking change in MySql.Data 8.0.31 package.
Removed `MySql.Data.MySqlClient.MySqlTrace.QueryAnalysisEnabled`
https://www.fuget.org/packages/MySql.Data/8.0.31/lib/netstandard2.1/diff/8.0.30/
