### ISSUE TITLE
Flaky test `WcfTestsBase`

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#1591]
Saw it already a few times

```
[xUnit.net 00:01:18.28]     IntegrationTests.WcfCoreTests.SubmitsTraces [FAIL]
  Failed IntegrationTests.WcfCoreTests.SubmitsTraces [6 s]
  Error Message:
   Expected process.ExitCode to be 0 because Test application exited with non-zero exit code, but found -532462766 (difference of -532462766).
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`2.Be(T expected, String because, Object[] becauseArgs)
   at IntegrationTests.Helpers.TestHelper.RunTestApplication(TestSettings testSettings) in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\IntegrationTests\Helpers\TestHelper.cs:line 114
   at IntegrationTests.WcfTestsBase.SubmitsTraces() in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\IntegrationTests\WcfTestsBase.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
 Found profiler at D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll.
 Found integrations at D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll.
 Platform: X64
 Configuration: Release
 TargetFramework: netcoreapp3.1
 .NET Core: True
 Profiler DLL: D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll
 Found profiler at D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll.
 Found integrations at D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll.
 Platform: X64
 Configuration: Release
 TargetFramework: netcoreapp3.1
 .NET Core: True
 Profiler DLL: D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll
 Waiting for WCF Server to open ports.
 WCF Server is running.
 Starting Application: D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\test-applications\integrations\TestApplication.Wcf.Client.Core\bin\x64\Release\netcoreapp3.1\TestApplication.Wcf.Client.Core.dll
 ProcessName: dotnet
 ProcessId: 6976
 Exit Code: -532462766
 StandardOutput:
 Server returned: 11/8/2022 1:04:25 PM +00:00
 
 StandardError:
 Unhandled exception. System.ServiceModel.CommunicationException: An error occurred while sending the request.
  ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
  ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
  ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
    --- End of inner exception stack trace ---
    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
    at System.Net.Http.HttpConnection.FillAsync()
    at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
    --- End of inner exception stack trace ---
    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
    at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.SendRequestAsync(Message message, TimeoutHelper timeoutHelper)
    --- End of inner exception stack trace ---
    at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
    at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
    at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
    at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
 --- End of stack trace from previous location where exception was thrown ---
    at TestApplication.Wcf.Client.Core.Program.CallService(Binding binding, EndpointAddress remoteAddress) in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\test-applications\integrations\TestApplication.Wcf.Client.Core\Program.cs:line 49
    at TestApplication.Wcf.Client.Core.Program.CallService(Binding binding, EndpointAddress remoteAddress) in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\test-applications\integrations\TestApplication.Wcf.Client.Core\Program.cs:line 72
    at TestApplication.Wcf.Client.Core.Program.Main() in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\test-applications\integrations\TestApplication.Wcf.Client.Core\Program.cs:line 33
    at TestApplication.Wcf.Client.Core.Program.<Main>()
 
 [MockSpansCollector]: Shutting down.
 [TestHttpServer]: Listener is shutting down.
 ProcessId: 5812
 Exit Code: -1
 StandardOutput:
 Server waiting for calls
 Server waiting for calls
 WCFServer: exiting main()
```

Maybe the test needs some "retry" or "healthz" as we get `System.ServiceModel.CommunicationException: An error occurred while sending the request.` Looks like `WaitForServer` is not good enough.

**Comment by pellared** [comment]
@dszmigielski could you take a look at it?

**Comment by dszmigielski** [comment]
> @dszmigielski could you take a look at it?

sure :)

**Comment by pellared** [comment]
Fails for FX as well https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/3420992192/jobs/5696528739
