### ISSUE TITLE
Fix integration tests

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#192]
Following integration tests started to fail as of https://dev.azure.com/opentelemetry/pipelines/_build/results?buildId=3778&view=results after merging https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/182
:

```
[xUnit.net 00:02:10.04]     Datadog.Trace.ClrProfiler.IntegrationTests.SmokeTests.AssemblyLoadFileNotFoundExceptionSmokeTest.NoExceptions [FAIL]
  Failed Datadog.Trace.ClrProfiler.IntegrationTests.SmokeTests.AssemblyLoadFileNotFoundExceptionSmokeTest.NoExceptions [704 ms]
  Error Message:
   Non-success exit code -10
Expected: True
Actual:   False
  Stack Trace:
     at Datadog.Trace.ClrProfiler.IntegrationTests.SmokeTests.SmokeTestBase.CheckForSmoke(Boolean shouldDeserializeTraces) in D:\a\1\s\test\Datadog.Trace.ClrProfiler.IntegrationTests\SmokeTests\SmokeTestBase.cs:line 148
   at Datadog.Trace.ClrProfiler.IntegrationTests.SmokeTests.AssemblyLoadFileNotFoundExceptionSmokeTest.NoExceptions() in D:\a\1\s\test\Datadog.Trace.ClrProfiler.IntegrationTests\SmokeTests\AssemblyLoadFileNotFoundExceptionSmokeTest.cs:line 22
  Standard Output Messages:
 Application path: D:\a\1\s\test/test-applications/regression\AssemblyLoad.FileNotFoundException\bin\X64\Release\net5.0\AssemblyLoad.FileNotFoundException.dll
 Executable path: dotnet.exe
 Assigning port 55649 for the agentPort.
 Assigning port 55650 for the aspNetCorePort.
 Found profiler at D:\a\1\s\test/test-applications/regression\AssemblyLoad.FileNotFoundException\bin\X64\Release\net5.0\profiler-lib\OpenTelemetry.AutoInstrumentation.ClrProfiler.Native.dll.
 Found integrations at D:\a\1\s\test/test-applications/regression\AssemblyLoad.FileNotFoundException\bin\X64\Release\net5.0\profiler-lib\integrations.json.
 StandardError:
 System.IO.FileNotFoundException: Could not load file or assembly 'OpenTelemetry.AutoInstrumentation.ClrProfiler.Managed, Version=0.0.1.0, Culture=neutral, PublicKeyToken=34b8972644a12429'. The system cannot find the file specified.
 File name: 'OpenTelemetry.AutoInstrumentation.ClrProfiler.Managed, Version=0.0.1.0, Culture=neutral, PublicKeyToken=34b8972644a12429'
    at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Net.Http.HttpClient.<>n__0(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
    at AssemblyLoad.FileNotFoundException.Program.Main() in D:\a\1\s\test\test-applications\regression\AssemblyLoad.FileNotFoundException\Program.cs:line 16


[xUnit.net 00:01:30.03] Datadog.Trace.ClrProfiler.IntegrationTests: STARTED: Datadog.Trace.ClrProfiler.IntegrationTests.AdoNet.SystemDataSqliteTests.SpansDisabledByAdoNetExcludedTypes(True)
  Failed Datadog.Trace.ClrProfiler.IntegrationTests.AdoNet.SystemDataSqliteTests.SpansDisabledByAdoNetExcludedTypes(enableCallTarget: False) [1 s]
  Error Message:
   Process exited with code -532462766
Expected: True
Actual:   False
  Stack Trace:
     at Datadog.Trace.ClrProfiler.IntegrationTests.AdoNet.SystemDataSqliteTests.SpansDisabledByAdoNetExcludedTypes(Boolean enableCallTarget) in D:\a\1\s\test\Datadog.Trace.ClrProfiler.IntegrationTests\AdoNet\SystemDataSqliteTests.cs:line 88
  Standard Output Messages:
 Platform: X64
 Configuration: Release
 TargetFramework: net461
 .NET Core: False
 Attempt 1: Unable to find profiler at D:\a\1\s\test/test-applications/integrations\Samples.SQLite.Core\bin\X64\Release\net461\profiler-lib\OpenTelemetry.AutoInstrumentation.ClrProfiler.Native.dll.
 Found profiler at D:\a\1\s\test\Datadog.Trace.ClrProfiler.IntegrationTests\bin\x64\Release\net461\profiler-lib\OpenTelemetry.AutoInstrumentation.ClrProfiler.Native.dll.
 Profiler DLL: D:\a\1\s\test\Datadog.Trace.ClrProfiler.IntegrationTests\bin\x64\Release\net461\profiler-lib\OpenTelemetry.AutoInstrumentation.ClrProfiler.Native.dll
 Starting Application: D:\a\1\s\test/test-applications/integrations\Samples.SQLite.Core\bin\X64\Release\net461\Samples.SQLite.Core.exe
 Attempt 1: Unable to find integrations at D:\a\1\s\test/test-applications/integrations\Samples.SQLite.Core\bin\X64\Release\net461\profiler-lib\integrations.json.
 Found integrations at D:\a\1\s\test\Datadog.Trace.ClrProfiler.IntegrationTests\bin\x64\Release\net461\profiler-lib\integrations.json.
 ProcessId: 448
 Exit Code: -532462766
 StandardError:
 
 Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
    at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
    at System.Data.SQLite.SQLite3.StaticIsInitialized()
    at System.Data.SQLite.SQLiteLog.Initialize(String className)
    at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
    at Samples.SQLite.Core.Program.OpenConnection()
    at Samples.SQLite.Core.Program.<Main>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
    at Samples.SQLite.Core.Program.<Main>()
```

Maybe the MSBuild version bump has caused the issues?

@zacharycmontoya @tonyredondo Have you encountered the same issue in Datadog repo?

**Comment by zacharycmontoya** [comment]
For `AssemblyLoadFileNotFoundExceptionSmokeTest`, this test regressed when enabling CallTarget by default in #182 . This will be fixed by the following commit, but it is not currently included in the upstream sync: https://github.com/DataDog/dd-trace-dotnet/commit/86dd06ada140fd7f766634f1f8fd6daa978f6894

**Comment by pellared** [comment]
No longer valid.
