### ISSUE TITLE
Could not load file or assembly `System.Diagnostics.DiagnosticSource`

### ISSUE THREAD

**Issue by Nemeczek** [open-telemetry/opentelemetry-dotnet-instrumentation#2077]
# Bug Report

## Symptom

**Describe the bug**
Auto instrumentation crashes on startup.

**Runtime environment (please complete the following information):**

- /azure-functions/dotnet:4 docker image so system is Debian 11
- OpenTelemetry Automatic Instrumentation version: 0.5.0
- OS: Debian 11
- .NET version: 6

````
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'OpenTelemetry.AutoInstrumentation.Loader.Startup' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileLoadException: Could not load file or assembly 'Google.Protobuf, Version=3.19.4.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'. Could not find or load a specific file. (0x80131621)
File name: 'Google.Protobuf, Version=3.19.4.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'
 ---> System.IO.FileLoadException: Could not load file or assembly 'Google.Protobuf, Version=3.19.4.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at OpenTelemetry.Exporter.OtlpTraceExporter..ctor
   at OpenTelemetry.Trace.OtlpTraceExporterHelperExtensions.AddOtlpExporter(TracerProviderBuilder builder, OtlpExporterOptions exporterOptions, Action`1 configure, IServiceProvider serviceProvider, Func`2 configureExporterInstance)
   at OpenTelemetry.AutoInstrumentation.Configuration.EnvironmentConfigurationTracerHelper.Wrappers.AddOtlpExporter(TracerProviderBuilder builder, TracerSettings settings, PluginManager pluginManager) in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation/Configuration/EnvironmentConfigurationTracerHelper.cs:line 185
   at OpenTelemetry.AutoInstrumentation.Configuration.EnvironmentConfigurationTracerHelper.SetExporter(TracerProviderBuilder builder, TracerSettings settings, PluginManager pluginManager) in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation/Configuration/EnvironmentConfigurationTracerHelper.cs:line 79
   at OpenTelemetry.AutoInstrumentation.Configuration.EnvironmentConfigurationTracerHelper.UseEnvironmentVariables(TracerProviderBuilder builder, LazyInstrumentationLoader lazyInstrumentationLoader, TracerSettings settings, PluginManager pluginManager) in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation/Configuration/EnvironmentConfigurationTracerHelper.cs:line 57
   at OpenTelemetry.AutoInstrumentation.Instrumentation.Initialize() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs:line 119
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenTelemetry.AutoInstrumentation.Loader.Startup.TryLoadManagedAssembly() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation.Loader/Startup.cs:line 52
   at OpenTelemetry.AutoInstrumentation.Loader.Startup..cctor() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation.Loader/Startup.cs:line 47
   --- End of inner exception stack trace ---
   at OpenTelemetry.AutoInstrumentation.Loader.Startup..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at StartupHook.Initialize() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation.StartupHook/StartupHook.cs:line 68
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath startupHook)
   at System.StartupHookProvider.ProcessStartupHooks()
````

**Comment by pellared** [comment]
Is your application using `Google.Protobuf`? If so please make sure to reference the `3.19.4.0` version.

More: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/troubleshooting.md#assembly-version-conflicts

**Comment by Nemeczek** [comment]
Yes, I have it because it is trasitive depedency of Microsoft.Azure.WebJobs.Extensions.Kafka:
```
 <PackageReference Include="Google.Protobuf" Version="3.19.4" />
 <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Kafka" Version="3.8.0" />
```

Same issue after pinning the version to 3.19.4.

**Comment by pellared** [comment]
Can you please try to [create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by Nemeczek** [comment]
Sorry for the trouble. I was inspecting the wrong Pod. 

The Google.Protobuf error is happening in the Pod where we do Auto Instrumentation Injection.

In this Pod the actual error was almost the same but about 
`<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="7.0.0" />`

After I removed it from .csproj the auto instrumentation works again.

**Comment by Nemeczek** [comment]
> Can you please [create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?
> 
> You can also consider [checking the logs](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/troubleshooting.md#collect-debug-logs) beforehand. There is a chance we will find some issue there.

I closed the issue but now I think if this bug should be reported here, or in operator repo? Because when I did auto-instrumentation in Dockerfile it worked. But when I try to inject it using k8s it does not. SO I think there is relation between project having Google.Protobuf installed and the fact if you autointrument before running you application (in dockerfile) vs injection into build image.

**Comment by pellared** [comment]
Please report it in https://github.com/open-telemetry/opentelemetry-operator/ with [create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) and ping @open-telemetry/dotnet-instrumentation-maintainers in the issue 😉 We will do our best to resolve the issue.

**Comment by Nemeczek** [comment]
> Please report it in https://github.com/open-telemetry/opentelemetry-operator/ with [create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example). Make sure to ping @open-telemetry/dotnet-instrumentation-maintainers in the issue 😉 We will do our best to resolve the issue.

I will, thanks.
