### ISSUE TITLE
v0.5.1-beta.2 ModuleTests failed on .NET framework 4.6.2

### ISSUE THREAD

**Issue by muhaook** [open-telemetry/opentelemetry-dotnet-instrumentation#2224]
## Symptom
**Describe the bug**
v0.5.1-beta.2 integration test ModuleTests failed on .NET framework 4.6.2. it succeeded in the past and started to fail after I built v0.6.0-beta.2 on the same Windows. (build v0.6.0-beta.2 succeeded; it was the v0.5.1-beta.2 build failed afterward) I doubt some libs such as OTel SDK left on the machine and tried `dotnet nuget locals all --clear`, but no luck.

```
19:33:04 [DBG] Failed!  - Failed:     3, Passed:    36, Skipped:     0, Total:    39, Duration: 2 m 10 s - IntegrationTests.dll (net462)
19:33:04 [ERR] Target RunManagedIntegrationTests has thrown an exception
Nuke.Common.Tooling.ProcessException: Process 'dotnet.exe' exited with code 1.
   > "C:\Program Files\dotnet\dotnet.exe" msbuild C:\muwork\shared\mikebitbucket\otel-dotnet-auto\test\IntegrationTests\IntegrationTests.csproj /target:VSTest /property:Configuration=Release /property:Platform=x64 /property:VSTestTestCaseFilter="Containers!=Windows" /property:VSTestBlameHang=True /property:VSTestBlameHangTimeout=5m /property:VSTestLogger=trx /property:VSTestResultsDirectory=C:\muwork\shared\mikebitbucket\otel-dotnet-auto\build_data\results\IntegrationTests /property:VSTestNoBuild=True
   @ C:\muwork\shared\mikebitbucket\otel-dotnet-auto
Error output:
   [xUnit.net 00:00:14.18]     IntegrationTests.ModuleTests.Default [FAIL]
   [xUnit.net 00:00:15.33]     IntegrationTests.ModuleTests.Minimal [FAIL]
   [xUnit.net 00:00:16.52]     IntegrationTests.ModuleTests.DefaultNoExporters [FAIL]

   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process) in /_/source/Nuke.Common/Tooling/ProcessExtensions.cs:line 39
   at Nuke.Common.Tools.DotNet.DotNetTasks.DotNetMSBuild(DotNetMSBuildSettings toolSettings) in /_/source/Nuke.Common/Tools/DotNet/DotNet.Generated.cs:line 649
   at Nuke.Common.Tools.DotNet.DotNetTasks.DotNetMSBuild(Configure`1 configurator) in /_/source/Nuke.Common/Tools/DotNet/DotNet.Generated.cs:line 676
   at Build.<get_RunManagedIntegrationTests>b__88_1() in C:\muwork\shared\mikebitbucket\otel-dotnet-auto\build\Build.Steps.cs:line 336
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 18
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
```
**Runtime environment:**

- OpenTelemetry Automatic Instrumentation version: 0.5.1-beta.2
- OS: Windows 10
- .NET version: .NET Framework 4.6.2

**Additional context**
error details:
```
19:31:04 [ERR] [xUnit.net 00:00:16.52]     IntegrationTests.ModuleTests.DefaultNoExporters [FAIL]
19:31:04 [DBG] [xUnit.net 00:00:16.52] IntegrationTests: === RUN   IntegrationTests.ProcessTests.SubmitMetrics()
19:31:04 [DBG]   Failed IntegrationTests.ModuleTests.DefaultNoExporters [1 s]
19:31:04 [DBG]   Error Message:
19:31:04 [DBG]    VerifyException : Directory: C:\muwork\shared\mikebitbucket\otel-dotnet-auto\test\IntegrationTests
19:31:04 [DBG] NotEqual:
19:31:04 [DBG]   - Received: ModuleTests.DefaultNoExporters.NetFx.Net4_6.received.txt
19:31:04 [DBG]     Verified: ModuleTests.DefaultNoExporters.NetFx.verified.txt
19:31:04 [DBG]
19:31:04 [DBG] FileContent:
19:31:04 [DBG]
19:31:04 [DBG] NotEqual:
19:31:04 [DBG]
19:31:04 [DBG] Received: ModuleTests.DefaultNoExporters.NetFx.Net4_6.received.txt
19:31:04 [DBG] [
19:31:04 [DBG]   OpenTelemetry,
19:31:04 [DBG]   OpenTelemetry.Api,
19:31:04 [DBG]   OpenTelemetry.Api.ProviderBuilderExtensions,
19:31:04 [DBG]   OpenTelemetry.AutoInstrumentation,
19:31:04 [DBG]   OpenTelemetry.AutoInstrumentation.Loader,
19:31:04 [DBG]   OpenTelemetry.Exporter.OpenTelemetryProtocol,
19:31:04 [DBG]   OpenTelemetry.Instrumentation.Process,
19:31:04 [DBG]   OpenTelemetry.Instrumentation.Runtime
19:31:04 [DBG] ]
19:31:04 [DBG] Verified: ModuleTests.DefaultNoExporters.NetFx.verified.txt
19:31:04 [DBG] [
19:31:04 [DBG]   OpenTelemetry,
19:31:04 [DBG]   OpenTelemetry.Api,
19:31:04 [DBG]   OpenTelemetry.AutoInstrumentation,
19:31:04 [DBG]   OpenTelemetry.AutoInstrumentation.Loader,
19:31:04 [DBG]   OpenTelemetry.Exporter.OpenTelemetryProtocol,
19:31:04 [DBG]   OpenTelemetry.Instrumentation.Process,
19:31:04 [DBG]   OpenTelemetry.Instrumentation.Runtime
19:31:04 [DBG] ]
19:31:04 [DBG]
19:31:04 [DBG]
19:31:04 [DBG]   Standard Output Messages:
19:31:04 [DBG]  Found profiler at C:\muwork\shared\mikebitbucket\otel-dotnet-auto\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll.
19:31:04 [DBG]  Found integrations at C:\muwork\shared\mikebitbucket\otel-dotnet-auto\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll.
19:31:04 [DBG]  Platform: X64
19:31:04 [DBG]  Configuration: Release
19:31:04 [DBG]  TargetFramework: net462
19:31:04 [DBG]  .NET Core: False
19:31:04 [DBG]  Profiler DLL: C:\muwork\shared\mikebitbucket\otel-dotnet-auto\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll
19:31:04 [DBG]  Starting Application: C:\muwork\shared\mikebitbucket\otel-dotnet-auto\test\test-applications\integrations\TestApplication.Modules\bin\x64\Release\net462\TestApplication.Modules.exe
19:31:04 [DBG]  ProcessName: TestApplication.Modules
19:31:04 [DBG]  ProcessId: 12968
19:31:04 [DBG]  Exit Code: 0
19:31:04 [DBG]  StandardOutput:
19:31:04 [DBG]  Command line: --temp-path C:\Users\mike\AppData\Local\Temp\tmpBF64.tmp
19:31:04 [DBG]  Platform: x64
19:31:04 [DBG]  Environment variables:
19:31:04 [DBG]          COR_ENABLE_PROFILING = 1
19:31:04 [DBG]          COR_PROFILER = {918728DD-259F-4A6A-AC2B-B85E1B658318}
19:31:04 [DBG]          COR_PROFILER_PATH = C:\muwork\shared\mikebitbucket\otel-dotnet-auto\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll
19:31:04 [DBG]          CORECLR_PROFILER = {918728DD-259F-4A6A-AC2B-B85E1B658318}
19:31:04 [DBG]          CORECLR_PROFILER_PATH = C:\muwork\shared\mikebitbucket\otel-dotnet-auto\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll
19:31:04 [DBG]          DOTNET_ADDITIONAL_DEPS = C:\muwork\shared\mikebitbucket\otel-dotnet-auto\bin\tracer-home\AdditionalDeps
19:31:04 [DBG]          DOTNET_CLI_TELEMETRY_OPTOUT = 1
19:31:04 [DBG]          DOTNET_EXE = C:\Program Files\dotnet\dotnet.exe
19:31:04 [DBG]          DOTNET_HOST_PATH = C:\Program Files\dotnet\dotnet.exe
19:31:04 [DBG]          DOTNET_MULTILEVEL_LOOKUP = 0
19:31:04 [DBG]          DOTNET_ROOT_X64 = C:\Program Files\dotnet
19:31:04 [DBG]          DOTNET_SHARED_STORE = C:\muwork\shared\mikebitbucket\otel-dotnet-auto\bin\tracer-home\store
19:31:04 [DBG]          DOTNET_SKIP_FIRST_TIME_EXPERIENCE = 1
19:31:04 [DBG]          DOTNET_STARTUP_HOOKS = C:\muwork\shared\mikebitbucket\otel-dotnet-auto\bin\tracer-home\net\OpenTelemetry.AutoInstrumentation.StartupHook.dll
19:31:04 [DBG]          OTEL_DOTNET_AUTO_DEBUG = 1
19:31:04 [DBG]          OTEL_DOTNET_AUTO_HOME = C:\muwork\shared\mikebitbucket\otel-dotnet-auto\bin\tracer-home
19:31:04 [DBG]          OTEL_DOTNET_AUTO_INTEGRATIONS_FILE = C:\muwork\shared\mikebitbucket\otel-dotnet-auto\bin\tracer-home\integrations.json
19:31:04 [DBG]          OTEL_DOTNET_AUTO_LOG_DIRECTORY = C:\muwork\shared\mikebitbucket\otel-dotnet-auto\build_data\profiler-logs
19:31:04 [DBG]          OTEL_DOTNET_AUTO_TRACES_ADDITIONAL_SOURCES = TestApplication.*
19:31:04 [DBG]          OTEL_LOGS_EXPORTER = none
19:31:04 [DBG]          OTEL_METRICS_EXPORTER = none
19:31:04 [DBG]          OTEL_TRACES_EXPORTER = none
```

**Comment by RassK** [comment]
Something is adding and loading `OpenTelemetry.Api.ProviderBuilderExtensions` extra.

**Comment by pellared** [comment]
Could it be caused by some trash in GAC?

**Comment by muhaook** [comment]
I found OTel SDK DLLs in GAC (attached a screenshot). Looks like they were left there when I was running `dotnet nuke` or `dotnet nuke workflow` against v0.6.0-beta.2. 

could you please confirm that `dotnet nuke workflow` register OTel SDK into GAC? if yes, looks like we should undo the registering at the end of `dotnet nuke workflow` 


![gac_otel_assembly](https://user-images.githubusercontent.com/52417764/220167814-cc2cbd7a-6b8e-4d53-beb6-5d4d69175a93.png)

**Comment by Kielek** [comment]
`nuke Workflow` is copying files into GAC.
We have decided to not include Uregistration into this pipeline.
Please check https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/3d3f5c395ac6eb0a2d774f25c87c9f74b2a8f266/build/Build.Steps.Windows.cs#L189-L196
and use `nuke UninstallNetFxAssembliesGAC` if you are fine with the risk.

**Comment by muhaook** [comment]
a quick question: do we have the same risk during uninstall: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/3d3f5c395ac6eb0a2d774f25c87c9f74b2a8f266/OpenTelemetry.DotNet.Auto.psm1#L303

**Comment by muhaook** [comment]
verified that removing OTel DLLs from GAC fixed this issue. I was using this script to remove OTel DLLs:
```
    [System.Reflection.Assembly]::Load("System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a") | Out-Null
    $publish = New-Object System.EnterpriseServices.Internal.Publish 
    $dlls = Get-ChildItem -Path .\netfx\ -Filter *.dll -File
    foreach ($dll in $dlls) {
        $publish.GacRemove($dll.FullName)
```

**Comment by muhaook** [comment]
I am closing this issue. looks like we can use `nuke workflow UninstallNetFxAssembliesGAC` to do a build and then clean it up (starting v0.6.0-beta.2). 
that said, removing a bunch of DLLs from GAC is really a concern to me.

**Comment by pjanotti** [comment]
Note: the method used to install/remove assemblies on the GAC only affect assemblies installed directly via the same COM API (e.g.: [`System.EnterpriseServices.Internal.Publish`](https://learn.microsoft.com/en-us/dotnet/api/system.enterpriseservices.internal.publish?view=netframework-4.8.1)) without reference counting. Applications that install assemblies to the GAC via MSIs (or even `gacutil` with reference counting) won't be affected by GAC removal done via `nuke UninstallNetFxAssembliesGAC`.

**Comment by muhaook** [comment]
It seems a risk in some edge cases. e.g. 
1. install otel auto-instrumentation which registered assemblies to GAC.
2. install another application which requires to use [System.EnterpriseServices.Internal.Publish](https://learn.microsoft.com/en-us/dotnet/api/system.enterpriseservices.internal.publish?view=netframework-4.8.1) to register a same assembly.
3. uninstall otel auto-instrumentation.

Is it a solution to use some tool with refetence counting to register assemblies during otel auto-instrumentation install?
