### ISSUE TITLE
ARM64 - support for opentelemetry-operator

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#2314]
# Feature Request

Based on ##2296. First we need #1865 and #2181.

**Comment by rkferreira** [comment]
Hi, it seems still not working for arm64 on Otel Operator for Auto Instrumentation.

**Comment by pjanotti** [comment]
Hi @rkferreira - could you provide details about the error that you are getting? In principle this work is done and we need some info to identify if this is an issue for dotnet-autoinstrumentation or the operator itself.

**Comment by navaneeth-dev** [comment]
With Jellyfin for example it loads x64 versions by default?

```bash
I have no name!@jellyfin-fbcbb88ff-985fq:/$ cat /tmp/otel-dotnet-auto-jellyfin-1-StartupHook-20260207.log
[2026-02-07T06:12:27.0805696Z] [Debug] Rule Engine: jellyfin is not in the exclusion list. ApplicationInExcludeListRule evaluation success.
[2026-02-07T06:12:27.1343173Z] [Information] Rule Engine: MinSupportedFrameworkRule evaluation success.
[2026-02-07T06:12:27.1379877Z] [Information] Rule Engine: OpenTelemetrySdkMinimumVersionRule evaluation success.
[2026-02-07T06:12:27.2082886Z] [Debug] Error checking if native profiler is attached.
Exception: Unable to load shared library '/otel-auto-instrumentation-dotnet/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
/otel-auto-instrumentation-dotnet/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so: cannot open shared object file: No such file or directory

System.DllNotFoundException: Unable to load shared library '/otel-auto-instrumentation-dotnet/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
/otel-auto-instrumentation-dotnet/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so: cannot open shared object file: No such file or directory

   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at OpenTelemetry.AutoInstrumentation.NativeMethods.ImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath) in /_/src/OpenTelemetry.AutoInstrumentation.StartupHook/NativeMethods.cs:line 39
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTelemetry.AutoInstrumentation.NativeMethods.IsProfilerAttached()
   at OpenTelemetry.AutoInstrumentation.RulesEngine.NativeProfilerDiagnosticsRule.Evaluate() in /_/src/OpenTelemetry.AutoInstrumentation.StartupHook/RulesEngine/NativeProfilerDiagnosticsRule.cs:line 58
[2026-02-07T06:12:27.2106723Z] [Error] CLR profiler was not correctly loaded into the process. Profiler found at '/otel-auto-instrumentation-dotnet/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so'. Recheck that 64bit process is attaching 64bit native profiler via CORECLR_PROFILER_PATH.
[2026-02-07T06:12:27.2123938Z] [Error] Rule 'Native profiler diagnoser' failed: Verifies that native profiler is correctly setup in case it's enabled.
[2026-02-07T06:12:27.2141736Z] [Error] Error in StartupHook initialization: LoaderFolderLocation: /otel-auto-instrumentation-dotnet/net
Exception: Rule Engine Failure: One or more rules failed validation. Automatic Instrumentation won't be loaded.
System.Exception: Rule Engine Failure: One or more rules failed validation. Automatic Instrumentation won't be loaded.
   at StartupHook.Initialize() in /_/src/OpenTelemetry.AutoInstrumentation.StartupHook/StartupHook.cs:line 47
```

**Comment by Kielek** [comment]
@navaneeth-dev, it is not (yet) supported. I think that all changes needs to go directly to opentelemetry-operator
 repository. Would you like to contribute?

**Comment by naman-jain-15** [comment]
HI @Kielek  
Could we get arm64 support for .NET auto-instrumentation in the operator? Wanted to check whether there's a blocker for runtime detection of arm64 in operator or if it's just pending someone picking it up.
Happy to contribute the change

**Comment by bhogayatakb** [comment]
Hello @Kielek, I have done a PR within opentelemetry-operator to resolve this. 
Please do verify. We can consider doing a release if these changes can help.

**Comment by marisofie** [comment]
Any updates on this? I am experiencing issues where AdditionalDeps cannot find the correct .Net version assembly, and it would be great to get the instrumentation working on arm64 in addition to amd64.

**Comment by Kielek** [comment]
@marisofie, arm64 should work without any issues if you set up it automatically,
This issue was to track work for operator. Technically, it was done under https://github.com/open-telemetry/opentelemetry-operator/pull/5350 and released within https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.158.0

Could you please be more descriptive what is not working?

This issue should be fixed when we have confirmation that operator is working with arm64.

**Comment by marisofie** [comment]
Ah, I see :) 

It looks like mye issue might be with the instrumentation itself, I am using the opentelemetry-operator v. 0.158.0. 
I get the following error using v. 1.13.0 of autoinstrumentation-dotnet and running on arm64: 

```
An assembly specified in the application dependencies manifest (OpenTelemetry.AutoInstrumentation.AdditionalDeps.deps.json) was not found: 
'Microsoft.Extensions.Configuration', version: '8.0.0' 
```

I can resolve this by setting the variables for finding the dependencies to "", i.e.:
```
ENV DOTNET_SHARED_STORE=""
ENV DOTNET_ADDITIONAL_DEPS=""
```

It would be great to resolve this in some other way though, as it seems like the setup when building on arm is not optimal. 

Let me know if you want me to comment on or create another issue since it is unrelated :)

**Comment by Kielek** [comment]
> Ah, I see :)
> 
> It looks like mye issue might be with the instrumentation itself, I am using the opentelemetry-operator v. 0.158.0. I get the following error using v. 1.13.0 of autoinstrumentation-dotnet and running on arm64:
> 
> ```
> An assembly specified in the application dependencies manifest (OpenTelemetry.AutoInstrumentation.AdditionalDeps.deps.json) was not found: 
> 'Microsoft.Extensions.Configuration', version: '8.0.0' 
> ```
> 
> I can resolve this by setting the variables for finding the dependencies to "", i.e.:
> 
> ```
> ENV DOTNET_SHARED_STORE=""
> ENV DOTNET_ADDITIONAL_DEPS=""
> ```
> 
> It would be great to resolve this in some other way though, as it seems like the setup when building on arm is not optimal.
> 
> Let me know if you want me to comment on or create another issue since it is unrelated :)

I would
1. Update your auto-instrumentation version to 1.16.0 (the latest at the time of writing).
2. Bring back the recommended values for mentioned `DOTNET_*` env. vars.

We have significantly improved dependency management in couple last releases. If it does not help, please create new issue with exact steps to reproduce.

**Comment by marisofie** [comment]
That worked, thank you for the help :)
