### ISSUE TITLE
Assembly version conflict between .NET application and auto-instrumentation

### ISSUE THREAD

**Issue by muhaook** [open-telemetry/opentelemetry-dotnet-instrumentation#2507]
I have .NET application which use OpenTelemetry.API.dll 1.3.1 for manual instrumetation. the OpenTelemetry.API.dll 1.3.1 is under the application directory. I then deployed dotnet-auto-instrumentation 0.6.0 which uses OpenTelemetry.API.dll 1.4.0. I found the OpenTelemetry.API.dll 1.3.1 got loaded by dotnet-auto-instrumentation which caused the application crash. This issue happened on both .net6 sample and .netfx48 sample.

## Issue on .NET 6 Sample
- OpenTelemetry Automatic Instrumentation version: 0.6.0
- OS: Windows 10
- .NET version: .NET 6

![image](https://user-images.githubusercontent.com/52417764/235754083-32d91bd7-20a6-469a-bc58-6aeec592f442.png)
```
[2023-05-02T18:30:19.1428409Z] [ThreadId: 1] Error when loading managed assemblies. Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MethodAccessException: Attempt by method 'OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracingServiceCollectionExtensions.RegisterBuildAction(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.Action`2<System.IServiceProvider,OpenTelemetry.Trace.TracerProviderBuilder>)' to access method 'OpenTelemetry.Internal.Guard.ThrowIfNull(System.Object, System.String)' failed.
   at OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracingServiceCollectionExtensions.RegisterBuildAction(IServiceCollection services, Action`2 configure)
   at OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracingServiceCollectionExtensions.ConfigureOpenTelemetryTracerProvider(IServiceCollection services, Action`2 configure)
   at OpenTelemetry.Trace.TracerProviderBuilderBase..ctor()
   at OpenTelemetry.Sdk.CreateTracerProviderBuilder()
   at OpenTelemetry.AutoInstrumentation.Instrumentation.Initialize() in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\src\OpenTelemetry.AutoInstrumentation\Instrumentation.cs:line 136
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OpenTelemetry.AutoInstrumentation.Loader.Loader.TryLoadManagedAssembly() in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\src\OpenTelemetry.AutoInstrumentation.Loader\Loader.cs:line 69
```
Please find the log here:
[logs_net6.zip](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/11376526/logs_net6.zip)

## Issue on .NET Framework 4.8 Sample
- OpenTelemetry Automatic Instrumentation version: 0.6.0
- OS: Windows 10
- .NET version: .NET Framework 4.8

![image](https://user-images.githubusercontent.com/52417764/235755070-6b253d12-6450-4be4-a6c3-2e41a2a76e73.png)
```
[2023-05-02T18:34:49.8696920Z] [ThreadId: 1] Error when loading managed assemblies. Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MethodAccessException: Attempt by method 'OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracingServiceCollectionExtensions.RegisterBuildAction(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.Action`2<System.IServiceProvider,OpenTelemetry.Trace.TracerProviderBuilder>)' to access method 'OpenTelemetry.Internal.Guard.ThrowIfNull(System.Object, System.String)' failed.
   at OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracingServiceCollectionExtensions.RegisterBuildAction(IServiceCollection services, Action`2 configure)
   at OpenTelemetry.Trace.TracerProviderBuilderBase..ctor()
   at OpenTelemetry.Sdk.CreateTracerProviderBuilder()
   at OpenTelemetry.AutoInstrumentation.Instrumentation.Initialize() in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\src\OpenTelemetry.AutoInstrumentation\Instrumentation.cs:line 176
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenTelemetry.AutoInstrumentation.Loader.Loader.TryLoadManagedAssembly() in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\src\OpenTelemetry.AutoInstrumentation.Loader\Loader.cs:line 54
```
Please find the log here:
[logs_netfx48.zip](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/files/11376554/logs_netfx48.zip)

## Question 1: 
I know we can do [assembly redirection](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/src/OpenTelemetry.AutoInstrumentation.Native/netfx_assembly_redirection.h) in .NET framework. Why assembly redirection from OpenTelemetry.API.dll 1.3.1 to OpenTelemetry.API.dll 1.4.0 did not happen in this issue? Is it because although the file version of the OpenTelemetry.API.dll is 1.3.1 or 1.4.0, their actual DLL version is the same as 1.0.0.0 ?

## Question 2: 
do we have an assembly version resolution mechanism in .NET 6, similar to the assembly redirection in .net framework?

## Question 3: 
if we have a dll in both application directory and tracer-home/net, which one takes precedence? looks like the one in application directory gets loaded.

**Comment by pjanotti** [comment]
A1.: Likely, as you noticed, the version of the file is the issue preventing the redirection in this case.

A2.: No, for .NET the best we have right now is using DOTNET_ADDITIONAL_DEPS and DOTNET_SHARED_STORE. However, they can't redirect a version of an assembly shipped with the application; they can upgrade a version from the framework itself. In this case, the version of the application needs to be updated to match the requirements from auto instrumentation (far from ideal).

A3.: The application one takes precedence, except for .NET Framework in which we can leverage the assembly redirection.

In general, having NuGet packages is the best general solution. However, that limits the usage to scenarios where the application can be rebuilt.

**Comment by muhaook** [comment]
Thanks @pjanotti , I do not quite understand the last sentence:
> In general, having NuGet packages is the best general solution. However, that limits the usage to scenarios where the application can be rebuilt.

Do you mean to rebuild the application and upgrade OpenTelemetry.API NuGet package to 1.4.0 in Visual Studio?

---

It is confusing why OpenTelemetry.API.dll FileVersion/ProductVersion got bumped up while AssemblyVersion didn't.

The versions of OpenTelemetry.API.dll:
- FileVersion: 1.4.0.802
- ProductVersion: 1.4.0+6f7878451397ebbf729f141381a934a3435a39fa
- AssemblyVersion: 1.0.0.0

```
PS C:\> (Get-Item C:\tracer-home\netfx\OpenTelemetry.Api.dll).VersionInfo | format-list
FileVersion       : 1.4.0.802
ProductVersion    : 1.4.0+6f7878451397ebbf729f141381a934a3435a39fa

PS C:\> [Reflection.AssemblyName]::GetAssemblyName('C:\tracer-home\netfx\OpenTelemetry.Api.dll')
Version        Name
-------        ----
1.0.0.0        OpenTelemetry.Api
```

**Comment by Kielek** [comment]
>> In general, having NuGet packages is the best general solution. However, that limits the usage to scenarios where the application can be rebuilt.
>
> Do you mean to rebuild the application and upgrade OpenTelemetry.API NuGet package to 1.4.0 in Visual Studio?

We have a plan to relase OpenTelemetry.AutomaticInstrumenation nuget package for 2 reasons.
 - using it as a way to ship OTel Auto and include it to the build output
 - just to sync. dependencies to avoid conflicts you have described

----

Assembly versioning: https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/versioning#assembly-version

**Comment by muhaook** [comment]
Thanks @Kielek , I'd like to try it out on my samples when OpenTelemetry.AutomaticInstrumenation nuget package is available. 
As far as I know, some customer have concern to introduce additional dependency in their project. OpenTelemetry.AutomaticInstrumenation may introduce a bunch of 4th party dependencies. Also, application needs to be rebuilt for AutomaticInstrumenation upgrade.

Looked at the doc. It makes sense to `keep the major version number of the AssemblyVersion and the NuGet package version in sync`.

**Comment by pjanotti** [comment]
SIG: this should be solved via the NuGet package. Further tests and validation are needed to confirm that.

**Comment by Kielek** [comment]
Closing this. It should be already solved by nuget package.
