### ISSUE TITLE
Auto Instrumentation causing system to behave erratically when enabled

### ISSUE THREAD

**Issue by noahjd** [open-telemetry/opentelemetry-dotnet-instrumentation#2800]
# Bug Report

## Symptom

**Describe the bug**
We are using the Auto Instrumentation for IIS and .NET Framework. Setting COR_ENABLE_PROFILING to 1 is causing my windows system to behave erratically. While the profiler is enabled, I cannot open Server Manager, Event Viewer, Powershell, IIS, etc... It's like the profiler is trying to get loaded with each of those processes. Here's an example of the error from event viewer (after disabling the profiler). After disabling it and logging off and back in again, the system works fine.

Application: ServerManager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoad(System.String, System.Security.Policy.Evidence, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoad(System.String, System.Security.Policy.Evidence, System.Threading.StackCrawlMark ByRef, Boolean)
   at System.Reflection.Assembly.Load(System.String)
   at OpenTelemetry.AutoInstrumentation.Loader.Loader.TryLoadManagedAssembly()
   at OpenTelemetry.AutoInstrumentation.Loader.Loader..cctor()

Exception Info: System.TypeInitializationException
   at OpenTelemetry.AutoInstrumentation.Loader.Loader..ctor()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)
   at System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, Boolean)
   at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[], System.Threading.StackCrawlMark ByRef)
   at System.Activator.CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
   at System.Reflection.Assembly.CreateInstance(System.String, Boolean, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
   at __DDVoidMethodType__.__DDVoidMethodCall__()
   at Microsoft.Windows.ServerManager.MainApplication.Main(System.String[])

**Expected behavior**
This should not be occurring

- OpenTelemetry Automatic Instrumentation version: 0.7.0
- OS: Windows Server 2022
- .NET version: .NET Framework 4.6.2

**Additional context**

## Reproduce

 1. COR_ENABLE_PROFILING set to 1
 2. After some time, it's not immediate, we cannot open system applications. 
 3. Application will not open.

Here's a log example of after trying to load just Server Manager

[2023-08-01T15:18:52.2343015Z] [Information] Managed Loader TryLoadManagedAssembly() 
[2023-08-01T15:18:52.7226865Z] [Error] Error when loading managed assemblies. Could not load file or assembly 'OpenTelemetry.AutoInstrumentation' or one of its dependencies. The system cannot find the file specified.
Exception: Could not load file or assembly 'OpenTelemetry.AutoInstrumentation' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'OpenTelemetry.AutoInstrumentation' or one of its dependencies. The system cannot find the file specified.
File name: 'OpenTelemetry.AutoInstrumentation'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at OpenTelemetry.AutoInstrumentation.Loader.Loader.TryLoadManagedAssembly()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by pjanotti** [comment]
Hi @noahjd - we don't recommend enabling the automatic instrumentation machine wide, since, typically, there are many processes that one is not interested in instrumenting, see https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/v0.7.0/docs/troubleshooting.md#solution-1

If you __must__ enable it system-wide I would recommend excluding various processes, see the config page for details.

We are getting close to releasing v1.0.0 if you could upgrade to that version it will be great.

**Comment by noahjd** [comment]
Hi @pjanotti, Thanks for your quick response. We didn't want to run it machine wide, we're still kind of learning how things work with OTEL. We moved the environment variables to the web.config via "<add key= xyz>" and now the system is stable again. Thanks for your help!
