### ISSUE TITLE
Flaky test `IntegrationTests.AspNet.AspNetTests.SubmitsTraces`

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#295]
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/4461872914?check_suite_focus=true

```
  Error: [xUnit.net 00:07:35.37]     IntegrationTests.AspNet.AspNetTests.SubmitsTraces [FAIL]
    Failed IntegrationTests.AspNet.AspNetTests.SubmitsTraces [7 m 27 s]
    Error Message:
     System.AggregateException : One or more errors occurred.
  ---- System.Threading.Tasks.TaskCanceledException : A task was canceled.
    Stack Trace:
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
     at IntegrationTests.AspNet.AspNetTests.SubmitsTraces() in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\integration-tests\aspnet\IntegrationTests.AspNet\AspNetTests.cs:line 32
  ----- Inner Stack Trace -----
  
    Standard Output Messages:
   Platform: X64
   Configuration: Release
   TargetFramework: net461
   .NET Core: False
   Found profiler at D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.ClrProfiler.Native.dll.
   Profiler DLL: D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.ClrProfiler.Native.dll
   PS> New-NetFirewallRule -DisplayName 'TraceAgent-50329' -Direction Inbound -LocalPort 50329 -Protocol TCP -Action Allow -Profile Any
   StandardOutput:
   
   
   Name                  : {7fb397b0-b8b2-42c6-8378-ff75acd3d750}
   DisplayName           : TraceAgent-50329
   Description           : 
   DisplayGroup          : 
   Group                 : 
   Enabled               : True
   Profile               : Any
   Platform              : {}
   Direction             : Inbound
   Action                : Allow
   EdgeTraversalPolicy   : Block
   LooseSourceMapping    : False
   LocalOnlyMapping      : False
   Owner                 : 
   PrimaryStatus         : OK
   Status                : The rule was parsed successfully from the store. (65536)
   EnforcementStatus     : NotApplicable
   PolicyStoreSource     : PersistentStore
   PolicyStoreSourceType : Local
   
   
   
   
   [MockZipkinCollector]: Running on port '50329'
   Zipkin Endpoint: http://10.1.1.1:50329/api/v2/spans
   Collecting docker logs to: D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\build_data\profiler-logs
   Container was started successfully: False
   [MockZipkinCollector]: Shutting down. Total spans received: '0'
   PS> Remove-NetFirewallRule -DisplayName TraceAgent-50329
```

I saw it a few times. I think here is the problem: `Container was started successfully: False`

@RassK any ideas? Should we do some retry?

**Comment by RassK** [comment]
Noticed also, seems container doesn't start any more in given time. Prob should increase timeout and / or verify that cached docker image is still used.

**Comment by pellared** [comment]
Reopening as this test is still unstable.

**Comment by pellared** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/403#issuecomment-1062784794

**Comment by RassK** [comment]
> [#403 (comment)](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/403#issuecomment-1062784794)

Seems to have multiple issues, as webapp is definitely up and running but loses spans 🤔

**Comment by RassK** [comment]
It was bug in handling retries when async timeout occurred. That's why no rows about retries. 
The interesting part is HttpClient's default request timeout is 100s, and it wasn't enough.

**Comment by pellared** [comment]
It is not flaky anymore.
