### ISSUE TITLE
gRPC loading issue on .NET Framework 4.8

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#3044]
Same issue on .NET Framework 4.8

Installed OTel packages:
OpenTelemetry _V1.6.0_
OpenTelemetry.Api _V1.6.0_
OpenTelemetry.Api.ProviderBuilderExtensions _V1.6.0_
OpenTelemetry.Exporter.Console _V1.6.0_
OpenTelemetry.Exporter.OpenTelemetryProtocol_V1.6.0_
OpenTelemetry.Extensions.Hosting _V1.6.0_
OpenTelemetry.Instrumentation.AspNet _V1.6.0-beta.1_
OpenTelemetry.Instrumentation.AspNet.TelemetryHtppModule _V1.6.0-beta.1_
OpenTelemetry.Instrumentation.Http _V1.5.1-beta.1_
OpenTelemetry.Instrumentation.SqlClient _V1.5.1-beta.1_

My GRPC packages are:
Grpc.Core.Api _V2.46.6_
Grpc _V2.46.6_
Grpc.Core _V2.46.6_

```
System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Grpc.Core\v4.0_2.0.0.0__d754f35622e28bad\grpc_csharp_ext.x64.dll,C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Grpc.Core\v4.0_2.0.0.0__d754f35622e28bad\runtimes/win-x64/native\grpc_csharp_ext.x64.dll,C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Grpc.Core\v4.0_2.0.0.0__d754f35622e28bad\../..\runtimes/win-x64/native\grpc_csharp_ext.x64.dll
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUsingExplicitLoad()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials)
   at OpenTelemetry.Exporter.OtlpExporterOptionsExtensions.CreateChannel(OtlpExporterOptions options)
   at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.ExportClient.OtlpGrpcTraceExportClient..ctor(OtlpExporterOptions options, TraceServiceClient traceServiceClient)
   at OpenTelemetry.Exporter.OtlpExporterOptionsExtensions.GetTraceExportClient(OtlpExporterOptions options)
   at OpenTelemetry.Exporter.OtlpTraceExporter..ctor(OtlpExporterOptions exporterOptions, SdkLimitOptions sdkLimitOptions, IExportClient`1 exportClient)
   at OpenTelemetry.Trace.OtlpTraceExporterHelperExtensions.BuildOtlpExporterProcessor(OtlpExporterOptions exporterOptions, SdkLimitOptions sdkLimitOptions, IServiceProvider serviceProvider, Func`2 configureExporterInstance)
   at OpenTelemetry.Trace.OtlpTraceExporterHelperExtensions.<>c__DisplayClass2_0.<AddOtlpExporter>b__1(IServiceProvider sp)
   at OpenTelemetry.Trace.TracerProviderBuilderExtensions.<>c__DisplayClass8_0.<AddProcessor>b__0(IServiceProvider sp, TracerProviderBuilder builder)
   at OpenTelemetry.Trace.OpenTelemetryDependencyInjectionTracingServiceCollectionExtensions.ConfigureTracerProviderBuilderCallbackWrapper.ConfigureBuilder(IServiceProvider serviceProvider, TracerProviderBuilder tracerProviderBuilder)
   at OpenTelemetry.Trace.TracerProviderSdk..ctor(IServiceProvider serviceProvider, Boolean ownsServiceProvider)
   at OpenTelemetry.Trace.TracerProviderBuilderBase.Build()
   at OpenTelemetry.Trace.TracerProviderBuilderBase.InvokeBuild()
   at OpenTelemetry.Trace.TracerProviderBuilderExtensions.Build(TracerProviderBuilder tracerProviderBuilder)
```

That workaround mentioned [here](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1647/files#diff-e2cbab6c133829f0514f81e69457054aebfdb5a0fda4a611f0b3fb7ee2f3b7b8) does not work for me unfortunately.

_Originally posted by @ClumsyPenguin in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1858#issuecomment-1780766108_

**Comment by Kielek** [comment]
@ClumsyPenguin, please track you issue separately.

Could you please be more descriptive with the issue?
What you are trying to achievie? If you really using automatic instrumentation or you are trying to establish it manually? https://github.com/open-telemetry/opentelemetry-dotnet

[Minimal, Reproducible example ](https://stackoverflow.com/help/minimal-reproducible-example) will be helpgull

**Comment by ClumsyPenguin** [comment]
I am using manual instrumentation through an interceptor in our common interfaces for Services, Repositories, Controllers, etc...

Previously i was using Jaeger exporter to view my traces in Jaeger UI. However since that package is deprecated i am trying to switch to the OTLP exporter at this moment.

The solution works, however when i switch to this new exporter it will crash with the above stacktrace.

I will try and provide an MVP later today.

**Comment by ClumsyPenguin** [comment]
@Kielek https://github.com/ClumsyPenguin/OtelExporter

This is a MVP i quickly puzzled together which reproduced the issue.


![image](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/assets/22469147/d21ed361-c50d-4da3-87fe-b2a46be873d2)

**Comment by Kielek** [comment]
@ClumsyPenguin, I do not think that your issues fits to this project. You are using fully manual instrumentation.
I would recommend to create issue under https://github.com/open-telemetry/opentelemetry-dotnet. You should find there better assistance.

**Comment by ClumsyPenguin** [comment]
I made a bug report on that repo, you can close this one.

**Comment by feitzi** [comment]
The problem still exists with OpenTelemetry.Exporter.OpenTelemetryProtocol version 1.13.1 on .NET Framework 4.8.
When adding the dependency and using .AddOtlpExporter(), the app fails to start with the following error:
```
Message: Service Startup threw Exception: Error loading native library. Not found in any of the possible locations: C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Grpc.Core\v4.0_2.0.0.0__d754f35622e28bad\grpc_csharp_ext.x64.dll,C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Grpc.Core\v4.0_2.0.0.0__d754f35622e28bad\runtimes/win-x64/native\grpc_csharp_ext.x64.dll,C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Grpc.Core\v4.0_2.0.0.0__d754f35622e28bad\../..\runtimes/win-x64/native\grpc_csharp_ext.x64.dll
Exception: System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible 
```

### To Reproduce

1. Be sure that you **not** have installed any version of .net 6+
2. Create a new project targeting .NET Framework 4.8.
3. Install OpenTelemetry.Exporter.OpenTelemetryProtocol v1.13.1.
4. Add .AddOtlpExporter() to the pipeline and run the app.
5. You will get an error
6. If you install .net (not .net framework) the app will run

**Comment by Kielek** [comment]
@feitzi, I think that you should report under https://github.com/open-telemetry/opentelemetry-dotnet.
[Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) is more than welcomed. It can be separate repository .It will be great if you can  encapsulate as Docker 

BTW closed issues are usually not watched. Consider creating separate tickets in such cases
