### ISSUE TITLE
AccessViolationException at NativeCallTargetDefinition

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#3199]
> Hi, I followed your documentation to add auto instrumentation https://opentelemetry.io/docs/instrumentation/net/automatic/nuget-packages/

Executing this command  "instrument.cmd Adp.ProductStore.Client.exe" throws the following issue. Any idea on the same please?

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at OpenTelemetry.AutoInstrumentation.NativeMethods+Windows.AddInstrumentations(System.String, OpenTelemetry.AutoInstrumentation.NativeCallTargetDefinition[], Int32)
--------------------------------
   at OpenTelemetry.AutoInstrumentation.NativeMethods.AddInstrumentations(System.String, OpenTelemetry.AutoInstrumentation.NativeCallTargetDefinition[])
   at OpenTelemetry.AutoInstrumentation.Instrumentation.RegisterBytecodeInstrumentations(Payload)
   at OpenTelemetry.AutoInstrumentation.Instrumentation.Initialize()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Span`1<System.Object> ByRef, System.Signature, Boolean, Boolean)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
   at OpenTelemetry.AutoInstrumentation.Loader.Loader.TryLoadManagedAssembly()
   at OpenTelemetry.AutoInstrumentation.Loader.Loader..cctor()
   at OpenTelemetry.AutoInstrumentation.Loader.Loader..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean)
   at System.Activator.CreateInstance(System.Type, Boolean, Boolean)
   at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Activator.CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
   at System.Reflection.Assembly.CreateInstance(System.String, Boolean, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
   at System.Reflection.Assembly.CreateInstance(System.String)
   at StartupHook.Initialize()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Span`1<System.Object> ByRef, System.Signature, Boolean, Boolean)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath)
   at System.StartupHookProvider.ProcessStartupHooks()

_Originally posted by @junaid-git in https://github.com/open-telemetry/opentelemetry.io/issues/3150#issuecomment-1868832221_

**Comment by Kielek** [comment]
@junaid-git, could you please share the [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) with us? It should include all required steps. Simple source code, executed commands, system, privileges you have, etc.

**Comment by pjanotti** [comment]
SIG: no repro, closing for now.
