### ISSUE TITLE
Flaky test: `IntegrationTests.DotNetCliTests.WorkFlow`

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-dotnet-instrumentation#3563]
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/10296118859/job/28497283365

```
Error: [xUnit.net 00:10:33.55]     IntegrationTests.DotNetCliTests.WorkFlow [FAIL]
  05:19:30 [ERR] [xUnit.net 00:10:33.55]     IntegrationTests.DotNetCliTests.WorkFlow [FAIL]
  05:19:30 [DBG] [xUnit.net 00:10:33.55] IntegrationTests: --- FAIL: IntegrationTests.DotNetCliTests.WorkFlow() (25.30s)
  05:19:30 [DBG] [xUnit.net 00:10:33.56] IntegrationTests: === RUN   IntegrationTests.QuartzTests.SubmitsTraces(3.10.0)
  05:19:30 [DBG]   Failed IntegrationTests.DotNetCliTests.WorkFlow [25 s]
  05:19:30 [DBG]   Error Message:
  05:19:30 [DBG]    Expected process.ExitCode to be 0 because Test application exited with non-zero exit code, but found 1 (difference of 1).
  05:19:30 [DBG]   Stack Trace:
  05:19:30 [DBG]      at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
  05:19:30 [DBG]    at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
  05:19:30 [DBG]    at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
  05:19:30 [DBG]    at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
  05:19:30 [DBG]    at FluentAssertions.Numeric.NumericAssertions`2.Be(T expected, String because, Object[] becauseArgs)
  05:19:30 [DBG]    at IntegrationTests.DotNetCliTests.RunDotNetCli(String arguments, String successMessage) in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/DotNetCliTests.cs:line 103
  05:19:30 [DBG]    at IntegrationTests.DotNetCliTests.WorkFlow() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/IntegrationTests/DotNetCliTests.cs:line 54
  05:19:30 [DBG]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
  05:19:30 [DBG]    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  05:19:30 [DBG]   Standard Output Messages:
  05:19:30 [DBG]  Found profiler at /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/bin/tracer-home/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so.
  05:19:30 [DBG]  Platform: x64
  05:19:30 [DBG]  Configuration: Release
  05:19:30 [DBG]  TargetFramework: net8.0
  05:19:30 [DBG]  .NET Core: True
  05:19:30 [DBG]  Profiler DLL: /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/bin/tracer-home/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so
  05:19:30 [DBG]  Running: dotnet build-server shutdown
  05:19:30 [DBG]  ProcessId: 13915
  05:19:30 [DBG]  Exit Code: 1
  05:19:30 [DBG]  StandardOutput:
  05:19:30 [DBG]  Shutting down MSBuild server...
  05:19:30 [DBG]  Shutting down VB/C# compiler server...
  05:19:30 [DBG]  VB/C# compiler server failed to shut down: The shutdown command failed: Error:
  05:19:30 [DBG]    An assembly specified in the application dependencies manifest (VBCSCompiler.deps.json) was not found:
  05:19:30 [DBG]      package: 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler', version: '4.10.0-3.24314.14'
  05:19:30 [DBG]      path: 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.dll'
  05:19:30 [DBG]  
  05:19:30 [DBG]  MSBuild server shut down successfully.
  05:19:30 [DBG]  
  05:19:30 [DBG]  Running: dotnet new console --framework net8.0
  05:19:30 [DBG]  ProcessId: 13945
  05:19:30 [DBG]  Exit Code: 0
  05:19:30 [DBG]  StandardOutput:
  05:19:30 [DBG]  The template "Console App" was created successfully.
  05:19:30 [DBG]  
  05:19:30 [DBG]  Processing post-creation actions...
  05:19:30 [DBG]  Restoring /tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj:
  05:19:30 [DBG]    Determining projects to restore...
  05:19:30 [DBG]    Restored /tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj (in 68 ms).
  05:19:30 [DBG]  Restore succeeded.
  05:19:30 [DBG]  
  05:19:30 [DBG]  
  05:19:30 [DBG]  
  05:19:30 [DBG]  Running: dotnet build
  05:19:30 [DBG]  ProcessId: 13970
  05:19:30 [DBG]  Exit Code: 1
  05:19:30 [DBG]  StandardOutput:
  05:19:30 [DBG]    Determining projects to restore...
  05:19:30 [DBG]    All projects are up-to-date for restore.
  Error:  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error : Error: [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  05:19:30 [ERR]  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error : Error: [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  Error:  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error :   An assembly specified in the application dependencies manifest (csc.deps.json) was not found: [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  05:19:30 [ERR]  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error :   An assembly specified in the application dependencies manifest (csc.deps.json) was not found: [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  Error:  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error :     package: 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler', version: '4.10.0-3.24314.14' [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  05:19:30 [ERR]  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error :     package: 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler', version: '4.10.0-3.24314.14' [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  Error:  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error :     path: 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.dll' [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  05:19:30 [ERR]  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error :     path: 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.dll' [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  05:19:30 [DBG]  
  05:19:30 [DBG]  Build FAILED.
  05:19:30 [DBG]  
  Error:  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error : Error: [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  05:19:30 [ERR]  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error : Error: [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  Error:  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error :   An assembly specified in the application dependencies manifest (csc.deps.json) was not found: [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  05:19:30 [ERR]  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error :   An assembly specified in the application dependencies manifest (csc.deps.json) was not found: [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  Error:  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error :     package: 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler', version: '4.10.0-3.24314.14' [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  05:19:30 [ERR]  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error :     package: 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler', version: '4.10.0-3.24314.14' [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  Error:  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error :     path: 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.dll' [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  05:19:30 [ERR]  /usr/share/dotnet/sdk/8.0.303/Roslyn/Microsoft.CSharp.Core.targets(85,5): error :     path: 'Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.dll' [/tmp/otel-dotnet-test-0c67a314e58e436fbf320e9183d70ddd/OTelDotNetCliTest/OTelDotNetCliTest.csproj]
  05:19:30 [DBG]      0 Warning(s)
  05:19:30 [DBG]      4 Error(s)
  05:19:30 [DBG]  
  05:19:30 [DBG]  Time Elapsed 00:00:20.77
```

**Comment by pellared** [comment]
Another failure: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/10296768474/job/28499161101

**Comment by pellared** [comment]
@pjanotti, related to https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/3522?

**Comment by pjanotti** [comment]
SIG: this shouldn't be necessary when we move to .NET 9 - keep open to track it.

**Comment by Kielek** [comment]
Closing. I do not saw any fails in this tests. Feel free to reopen when it occurs.
