### ISSUE TITLE
Rejit timeouts / failing apps with STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Kielek** [open-telemetry/opentelemetry-dotnet-instrumentation#3838]
`IntegrationTests.ModuleTests.Default()` is frequently failing. Mostly on [test-build-managed (net9.0, windows-2022)](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/12085659662/job/33703926134#logs).

The process is returning non-zero code:

```log
  13:54:30 [DBG] [xUnit.net 00:01:50.72] IntegrationTests: --- FAIL: IntegrationTests.ModuleTests.Default() (4.40s)
  13:54:30 [DBG]   Failed IntegrationTests.ModuleTests.Default [4 s]
  13:54:30 [DBG]   Error Message:
  13:54:30 [DBG]    Expected process.ExitCode to be 0 because Test application exited with non-zero exit code, but found -1073741819 (difference of -1073741819).
  13:54:30 [DBG]   Stack Trace:
  13:54:30 [DBG]      at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
  13:54:30 [DBG]    at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
  13:54:30 [DBG]    at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
  13:54:30 [DBG]    at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
  13:54:30 [DBG]    at FluentAssertions.Numeric.NumericAssertions`2.Be(T expected, String because, Object[] becauseArgs)
  13:54:30 [DBG]    at IntegrationTests.Helpers.TestHelper.RunTestApplication(TestSettings testSettings) in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\IntegrationTests\Helpers\TestHelper.cs:line 118
  13:54:30 [DBG]    at IntegrationTests.ModuleTests.RunTests(String verifyName) in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\IntegrationTests\ModuleTests.cs:line 82
  13:54:30 [DBG]    at IntegrationTests.ModuleTests.Default() in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\IntegrationTests\ModuleTests.cs:line 33
  13:54:30 [DBG] --- End of stack trace from previous location ---
  13:54:30 [DBG]   Standard Output Messages:
  13:54:30 [DBG]  Found profiler at D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll.
  13:54:30 [DBG]  Platform: x64
  13:54:30 [DBG]  Configuration: Release
  13:54:30 [DBG]  TargetFramework: net9.0
  13:54:30 [DBG]  .NET Core: True
  13:54:30 [DBG]  Profiler DLL: D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll
  13:54:30 [DBG]  DotnetCLI Starting Application: D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\test-applications\integrations\bin\TestApplication.Modules\x64\Release\net9.0\TestApplication.Modules.dll
  13:54:30 [DBG]  ProcessName: dotnet
  13:54:30 [DBG]  ProcessId: 5612
  13:54:30 [DBG]  Exit Code: -1073741819
  13:54:30 [DBG]  StandardOutput:
  13:54:30 [DBG]  Command line: --temp-path C:\Users\runneradmin\AppData\Local\Temp\tmpgznt4t.tmp
  13:54:30 [DBG]  Platform: x64
  13:54:30 [DBG]  Environment variables:
  13:54:30 [DBG]  	COR_ENABLE_PROFILING = 1
  13:54:30 [DBG]  	COR_PROFILER = {918728DD-259F-4A6A-AC2B-B85E1B658318}
  13:54:30 [DBG]  	COR_PROFILER_PATH = D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll
  13:54:30 [DBG]  	CORECLR_ENABLE_PROFILING = 1
  13:54:30 [DBG]  	CORECLR_PROFILER = {918728DD-259F-4A6A-AC2B-B85E1B658318}
  13:54:30 [DBG]  	CORECLR_PROFILER_PATH = D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll
  13:54:30 [DBG]  	DOTNET_ADDITIONAL_DEPS = D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\AdditionalDeps
  13:54:30 [DBG]  	DOTNET_CLI_TELEMETRY_OPTOUT = 1
  13:54:30 [DBG]  	DOTNET_EXE = C:\Program Files\dotnet\dotnet.exe
  13:54:30 [DBG]  	DOTNET_HOST_PATH = C:\Program Files\dotnet\dotnet.exe
  13:54:30 [DBG]  	DOTNET_MULTILEVEL_LOOKUP = 0
  13:54:30 [DBG]  	DOTNET_NOLOGO = 1
  13:54:30 [DBG]  	DOTNET_ROOT = C:\Program Files\dotnet
  13:54:30 [DBG]  	DOTNET_ROOT_X64 = C:\Program Files\dotnet
  13:54:30 [DBG]  	DOTNET_SHARED_STORE = D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\store
  13:54:30 [DBG]  	DOTNET_SKIP_FIRST_TIME_EXPERIENCE = 1
  13:54:30 [DBG]  	DOTNET_STARTUP_HOOKS = D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\net\OpenTelemetry.AutoInstrumentation.StartupHook.dll
  13:54:30 [DBG]  	OTEL_DOTNET_AUTO_HOME = D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home
  13:54:30 [DBG]  	OTEL_DOTNET_AUTO_LOG_DIRECTORY = D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test-artifacts\profiler-logs
  13:54:30 [DBG]  	OTEL_DOTNET_AUTO_TRACES_ADDITIONAL_SOURCES = TestApplication.*
  13:54:30 [DBG]  	OTEL_LOG_LEVEL = debug
```

**Comment by Kielek** [comment]
Some findings related to the failures:
It is failing when ClrProfiler is executed and following warning occurs in logs:
```log
Timeout while waiting for the rejit requests to be processed. Rejit will continue asynchronously, but some initial calls may not be instrumented
```

It affects at least:

* `IntegrationTests.LogTests.SubmitLogs(True, True)`
* `IntegrationTests.ModuleTests.Default`

Ref: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/12255067137/job/34187919645?pr=3877

Similar issue occurred also on older ci-executions. Correlation seems be important.

Log message in the code: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/253f173049b550b1f00ad9072755a3a4112eac60/src/OpenTelemetry.AutoInstrumentation.Native/cor_profiler.cpp#L784-L810

**Comment by Kielek** [comment]
Status exit code notes:

It is logged as: `-1073741819`

Based on https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55

it leads to 
0xC0000005 STATUS_ACCESS_VIOLATION | The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s.

**Comment by Kielek** [comment]
More error logs can be found within https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/12256313520/job/34192128514
