### ISSUE TITLE
Flaky test: `IntegrationTests.MongoDB.MongoDbTests.SubmitsTraces`

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#414]
Test `IntegrationTests.MongoDB.MongoDbTests.SubmitsTraces` failure that passed on the retry.

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/5575541741?check_suite_focus=true#step:5:3035

```terminal
  Error: [xUnit.net 00:05:23.93]     IntegrationTests.MongoDB.MongoDbTests.SubmitsTraces [FAIL]
  19:50:59 [ERR] [xUnit.net 00:05:23.93]     IntegrationTests.MongoDB.MongoDbTests.SubmitsTraces [FAIL]
  19:50:59 [DBG]   Failed IntegrationTests.MongoDB.MongoDbTests.SubmitsTraces [1 ms]
  19:50:59 [DBG]   Error Message:
  19:50:59 [DBG]    System.AggregateException : One or more errors occurred. (One or more errors occurred. (The operation has timed out.)) (The following constructor parameters did not have matching fixture data: MongoDbFixture mongoDb)
  19:50:59 [DBG] ---- System.AggregateException : One or more errors occurred. (The operation has timed out.)
  19:50:59 [DBG] -------- System.TimeoutException : The operation has timed out.
  19:50:59 [DBG] ---- The following constructor parameters did not have matching fixture data: MongoDbFixture mongoDb
  19:50:59 [DBG]   Stack Trace:
  19:50:59 [DBG]   
  19:50:59 [DBG] ----- Inner Stack Trace #1 (System.AggregateException) -----
  19:50:59 [DBG]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
  19:50:59 [DBG]    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
  19:50:59 [DBG]    at System.Threading.Tasks.Task.Wait()
  19:50:59 [DBG]    at IntegrationTests.MongoDB.MongoDbFixture.LaunchMongoContainer(Int32 port) in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\integration-tests\IntegrationTests.MongoDB\MongoDbCollection.cs:line 78
  19:50:59 [DBG]    at IntegrationTests.MongoDB.MongoDbFixture..ctor() in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\integration-tests\IntegrationTests.MongoDB\MongoDbCollection.cs:line 33
  19:50:59 [DBG] ----- Inner Stack Trace -----
  19:50:59 [DBG]    at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
  19:50:59 [DBG]    at System.IO.Pipes.NamedPipeClientStream.<>c__DisplayClass20_0.<ConnectAsync>b__0()
  19:50:59 [DBG]    at System.Threading.Tasks.Task.InnerInvoke()
  19:50:59 [DBG]    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
  19:50:59 [DBG]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
  19:50:59 [DBG] --- End of stack trace from previous location ---
  19:50:59 [DBG]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
  19:50:59 [DBG]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
  19:50:59 [DBG] --- End of stack trace from previous location ---
  19:50:59 [DBG]    at Docker.DotNet.DockerClient.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext()
  19:50:59 [DBG] --- End of stack trace from previous location ---
  19:50:59 [DBG]    at Microsoft.Net.Http.Client.ManagedHandler.ProcessRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  19:50:59 [DBG]    at Microsoft.Net.Http.Client.ManagedHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  19:50:59 [DBG]    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
  19:50:59 [DBG]    at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
  19:50:59 [DBG]    at Docker.DotNet.DockerClient.PrivateMakeRequestAsync(TimeSpan timeout, HttpCompletionOption completionOption, HttpMethod method, String path, IQueryString queryString, IDictionary`2 headers, IRequestContent data, CancellationToken cancellationToken)
  19:50:59 [DBG]    at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
  19:50:59 [DBG]    at Docker.DotNet.ExecOperations.InspectContainerExecAsync(String id, CancellationToken cancellationToken)
  19:50:59 [DBG]    at DotNet.Testcontainers.Clients.DockerContainerOperations.ExecAsync(String id, IList`1 command, CancellationToken ct)
  19:50:59 [DBG]    at DotNet.Testcontainers.Containers.WaitStrategies.Unix.UntilCommandIsCompleted.Until(Uri endpoint, String id)
  19:50:59 [DBG]    at DotNet.Testcontainers.Containers.WaitStrategies.WaitStrategy.<>c__DisplayClass1_0.<<WaitUntil>b__0>d.MoveNext()
  19:50:59 [DBG] --- End of stack trace from previous location ---
  19:50:59 [DBG]    at DotNet.Testcontainers.Containers.WaitStrategies.WaitStrategy.WaitUntil(Func`1 wait, Int32 frequency, Int32 timeout, CancellationToken ct)
  19:50:59 [DBG]    at DotNet.Testcontainers.Containers.Modules.TestcontainersContainer.Start(String id, CancellationToken ct)
  19:50:59 [DBG]    at DotNet.Testcontainers.Containers.Modules.TestcontainersContainer.StartAsync(CancellationToken ct)
  19:50:59 [DBG] ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
  19:50:59 [DBG] 
```

**Comment by pjanotti** [comment]
Same test, but different failure: just no spans captured https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/5724840141?check_suite_focus=true#step:5:3043

**Comment by pjanotti** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/5993633949?check_suite_focus=true#step:5:2964

**Comment by pellared** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/6205562490?check_suite_focus=true

```
Error: [xUnit.net 00:00:32.65]     IntegrationTests.MongoDB.MongoDbTests.SubmitsTraces [FAIL]
  06:02:56 [ERR] [xUnit.net 00:00:32.65]     IntegrationTests.MongoDB.MongoDbTests.SubmitsTraces [FAIL]
  06:02:56 [DBG]   Failed IntegrationTests.MongoDB.MongoDbTests.SubmitsTraces [31 s]
  06:02:56 [DBG]   Error Message:
  06:02:56 [DBG]    Process exited with code -532462766 and exception: Unhandled exception. System.TimeoutException: A timeout occurred after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 }, OperationsCountServerSelector }. Client view of cluster state is { ClusterId : "1", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/localhost:27017" }", EndPoint: "Unspecified/localhost:27017", ReasonChanged: "Heartbeat", State: "Disconnected", ServerVersion: , TopologyVersion: , Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server.
  06:02:56 [DBG]  ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::1]:27017
  06:02:56 [DBG]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
  06:02:56 [DBG]    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
  06:02:56 [DBG]    at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__274_0(IAsyncResult iar)
  06:02:56 [DBG] --- End of stack trace from previous location where exception was thrown ---
  06:02:56 [DBG]    at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync(Socket socket, EndPoint endPoint, CancellationToken cancellationToken)
  06:02:56 [DBG]    at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
  06:02:56 [DBG]    at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
  06:02:56 [DBG]    --- End of inner exception stack trace ---
  06:02:56 [DBG]    at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
  06:02:56 [DBG]    at MongoDB.Driver.Core.Servers.ServerMonitor.InitializeConnectionAsync(CancellationToken cancellationToken)
  06:02:56 [DBG]    at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastHeartbeatTimestamp: "2022-04-28T06:02:52.6591686Z", LastUpdateTimestamp: "2022-04-28T06:02:52.6591735Z" }] }.
  06:02:56 [DBG]    at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException(IServerSelector selector, ClusterDescription description)
  06:02:56 [DBG]    at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
  06:02:56 [DBG]    at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChanged(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
  06:02:56 [DBG]    at MongoDB.Driver.Core.Clusters.Cluster.SelectServer(IServerSelector selector, CancellationToken cancellationToken)
  06:02:56 [DBG]    at MongoDB.Driver.MongoClient.AreSessionsSupportedAfterServerSelection(CancellationToken cancellationToken)
  06:02:56 [DBG]    at MongoDB.Driver.MongoClient.AreSessionsSupported(CancellationToken cancellationToken)
  06:02:56 [DBG]    at MongoDB.Driver.MongoClient.StartImplicitSession(CancellationToken cancellationToken)
  06:02:56 [DBG]    at MongoDB.Driver.OperationExecutor.StartImplicitSession(CancellationToken cancellationToken)
  06:02:56 [DBG]    at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
  06:02:56 [DBG]    at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
  06:02:56 [DBG]    at MongoDB.Driver.MongoCollectionBase`1.<>c__DisplayClass31_0.<DeleteMany>b__0(IEnumerable`1 requests)
  06:02:56 [DBG]    at MongoDB.Driver.MongoCollectionBase`1.DeleteMany(FilterDefinition`1 filter, DeleteOptions options, Func`2 bulkWriteFunc)
  06:02:56 [DBG]    at MongoDB.Driver.MongoCollectionBase`1.DeleteMany(FilterDefinition`1 filter, DeleteOptions options, CancellationToken cancellationToken)
  06:02:56 [DBG]    at MongoDB.Driver.MongoCollectionBase`1.DeleteMany(FilterDefinition`1 filter, CancellationToken cancellationToken)
  06:02:56 [DBG]    at TestApplication.MongoDB.Program.Run(IMongoCollection`1 collection, BsonDocument newDocument) in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\test-applications\integrations\TestApplication.MongoDB\Program.cs:line 81
  06:02:56 [DBG]    at TestApplication.MongoDB.Program.Main(String[] args) in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\test-applications\integrations\TestApplication.MongoDB\Program.cs:line 65
  06:02:56 [DBG] 
  06:02:56 [DBG] Expected: True
  06:02:56 [DBG] Actual:   False
  06:02:56 [DBG]   Stack Trace:
  06:02:56 [DBG]      at IntegrationTests.MongoDB.MongoDbTests.SubmitsTraces() in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\integration-tests\IntegrationTests.MongoDB\MongoDbTests.cs:line 49
  06:02:56 [DBG]   Standard Output Messages:
  06:02:56 [DBG]  Platform: X64
  06:02:56 [DBG]  Configuration: Release
  06:02:56 [DBG]  TargetFramework: netcoreapp3.1
  06:02:56 [DBG]  .NET Core: True
  06:02:56 [DBG]  Found profiler at D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll.
  06:02:56 [DBG]  Profiler DLL: D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll
  06:02:56 [DBG]  [MockZipkinCollector]: Running on port '62412'
  06:02:56 [DBG]  Starting Application: D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\test-applications\integrations\TestApplication.MongoDB\bin\x64\Release\netcoreapp3.1\TestApplication.MongoDB.dll
  06:02:56 [DBG]  Found integrations at D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\bin\tracer-home\win-x64\OpenTelemetry.AutoInstrumentation.Native.dll.
  06:02:56 [DBG]  ProcessName: dotnet
  06:02:56 [DBG]  ProcessId: 1768
  06:02:56 [DBG]  Exit Code: -532462766
  06:02:56 [DBG]  StandardOutput:
  06:02:56 [DBG]  Command line: --mongo-db;27017
  06:02:56 [DBG]  Profiler attached: True
  06:02:56 [DBG]  Platform: x64
  06:02:56 [DBG]  
  06:02:56 [DBG]  StandardError:
  06:02:56 [DBG]  Unhandled exception. System.TimeoutException: A timeout occurred after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 }, OperationsCountServerSelector }. Client view of cluster state is { ClusterId : "1", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/localhost:27017" }", EndPoint: "Unspecified/localhost:27017", ReasonChanged: "Heartbeat", State: "Disconnected", ServerVersion: , TopologyVersion: , Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server.
  06:02:56 [DBG]   ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. [::1]:27017
  06:02:56 [DBG]     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
  06:02:56 [DBG]     at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
  06:02:56 [DBG]     at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__274_0(IAsyncResult iar)
  06:02:56 [DBG]  --- End of stack trace from previous location where exception was thrown ---
  06:02:56 [DBG]     at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync(Socket socket, EndPoint endPoint, CancellationToken cancellationToken)
  06:02:56 [DBG]     at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
  06:02:56 [DBG]     at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
  06:02:56 [DBG]     --- End of inner exception stack trace ---
  06:02:56 [DBG]     at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
  06:02:56 [DBG]     at MongoDB.Driver.Core.Servers.ServerMonitor.InitializeConnectionAsync(CancellationToken cancellationToken)
  06:02:56 [DBG]     at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastHeartbeatTimestamp: "2022-04-28T06:02:52.6591686Z", LastUpdateTimestamp: "2022-04-28T06:02:52.6591735Z" }] }.
  06:02:56 [DBG]     at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException(IServerSelector selector, ClusterDescription description)
  06:02:56 [DBG]     at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
  06:02:56 [DBG]     at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChanged(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
  06:02:56 [DBG]     at MongoDB.Driver.Core.Clusters.Cluster.SelectServer(IServerSelector selector, CancellationToken cancellationToken)
  06:02:56 [DBG]     at MongoDB.Driver.MongoClient.AreSessionsSupportedAfterServerSelection(CancellationToken cancellationToken)
  06:02:56 [DBG]     at MongoDB.Driver.MongoClient.AreSessionsSupported(CancellationToken cancellationToken)
  06:02:56 [DBG]     at MongoDB.Driver.MongoClient.StartImplicitSession(CancellationToken cancellationToken)
  06:02:56 [DBG]     at MongoDB.Driver.OperationExecutor.StartImplicitSession(CancellationToken cancellationToken)
  06:02:56 [DBG]     at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
  06:02:56 [DBG]     at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
  06:02:56 [DBG]     at MongoDB.Driver.MongoCollectionBase`1.<>c__DisplayClass31_0.<DeleteMany>b__0(IEnumerable`1 requests)
  06:02:56 [DBG]     at MongoDB.Driver.MongoCollectionBase`1.DeleteMany(FilterDefinition`1 filter, DeleteOptions options, Func`2 bulkWriteFunc)
  06:02:56 [DBG]     at MongoDB.Driver.MongoCollectionBase`1.DeleteMany(FilterDefinition`1 filter, DeleteOptions options, CancellationToken cancellationToken)
  06:02:56 [DBG]     at MongoDB.Driver.MongoCollectionBase`1.DeleteMany(FilterDefinition`1 filter, CancellationToken cancellationToken)
  06:02:56 [DBG]     at TestApplication.MongoDB.Program.Run(IMongoCollection`1 collection, BsonDocument newDocument) in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\test-applications\integrations\TestApplication.MongoDB\Program.cs:line 81
  06:02:56 [DBG]     at TestApplication.MongoDB.Program.Main(String[] args) in D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\test\test-applications\integrations\TestApplication.MongoDB\Program.cs:line 65
  06:02:56 [DBG]  
  06:02:56 [DBG]  [MockZipkinCollector]: Shutting down. Total spans received: '0'
  06:02:56 [DBG] 
  06:02:56 [DBG] 
  06:02:56 [DBG] Results File: D:\a\opentelemetry-dotnet-instrumentation\opentelemetry-dotnet-instrumentation\build_data\results\IntegrationTests.MongoDB\runneradmin_fv-az449-457_2022-04-28_06_02_56.trx
  06:02:56 [DBG] 
  06:02:56 [DBG] Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - IntegrationTests.MongoDB.dll (netcoreapp3.1)
```
