### ISSUE TITLE
Flaky test: (port already in use) `IntegrationTests.GraphQL.GraphQLTests.SubmitsTraces` 

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#424]
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/5724511365?check_suite_focus=true#step:5:1896

It failed to capture any span likely related to port already in use, it passed on next retry:
```
  17:18:55 [DBG]  [webserver][stdout]       Unable to start Kestrel.
  17:18:55 [DBG]  [webserver][stdout] System.IO.IOException: Failed to bind to address [http://127.0.0.1:37149:](http://127.0.0.1:37149/) address already in use.
```

Full logs for the test: 

```
Error: [xUnit.net 00:00:45.64]     IntegrationTests.GraphQL.GraphQLTests.SubmitsTraces [FAIL]
  17:18:55 [ERR] [xUnit.net 00:00:45.64]     IntegrationTests.GraphQL.GraphQLTests.SubmitsTraces [FAIL]
  17:18:55 [DBG]   Failed IntegrationTests.GraphQL.GraphQLTests.SubmitsTraces [44 s]
  17:18:55 [DBG]   Error Message:
  17:18:55 [DBG]    Expected at least 11 spans, received 0
  17:18:55 [DBG] Expected: True
  17:18:55 [DBG] Actual:   False
  17:18:55 [DBG]   Stack Trace:
  17:18:55 [DBG]      at IntegrationTests.Helpers.SpanTestHelpers.AssertExpectationsMet[T](List`1 expectations, List`1 spans) in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/integration-tests/IntegrationTests.Helpers/SpanTestHelpers.cs:line 35
  17:18:55 [DBG]    at IntegrationTests.GraphQL.GraphQLTests.SubmitsTraces() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/integration-tests/IntegrationTests.GraphQL/GraphQLTests.cs:line 174
  17:18:55 [DBG]   Standard Output Messages:
  17:18:55 [DBG]  Platform: X64
  17:18:55 [DBG]  Configuration: Release
  17:18:55 [DBG]  TargetFramework: netcoreapp3.1
  17:18:55 [DBG]  .NET Core: True
  17:18:55 [DBG]  Found profiler at /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/bin/tracer-home/OpenTelemetry.AutoInstrumentation.Native.so.
  17:18:55 [DBG]  Profiler DLL: /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/bin/tracer-home/OpenTelemetry.AutoInstrumentation.Native.so
  17:18:55 [DBG]  [MockZipkinCollector]: Running on port '34845'
  17:18:55 [DBG]  Starting Application: /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/test-applications/integrations/Samples.GraphQL/bin/x64/Release/netcoreapp3.1/Samples.GraphQL.dll
  17:18:55 [DBG]  Found integrations at /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/bin/tracer-home/OpenTelemetry.AutoInstrumentation.Native.so.
  17:18:55 [DBG]  [webserver][stdout] >>>>>>>>>>>>>>>>>>>>>>> Process: dotnet(3788): OpenTelemetry tracer initialized.
  17:18:55 [DBG]  [webserver][stdout] >>>>>>>>>>>>>>>>>>>>>>> Process: dotnet(3788): OpenTracingShim loaded.
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       Instrumentation.ProfilerAttached = True
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       CORECLR_ENABLE_PROFILING = 1
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       CORECLR_PROFILER = {918728DD-259F-4A6A-AC2B-B85E1B658318}
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       CORECLR_PROFILER_PATH = /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/bin/tracer-home/OpenTelemetry.AutoInstrumentation.Native.so
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       DOTNET_CLI_TELEMETRY_OPTOUT = 1
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       DOTNET_EXE = /home/runner/.dotnet/dotnet
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       DOTNET_HOST_PATH = /home/runner/.dotnet/dotnet
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       DOTNET_MULTILEVEL_LOOKUP = 0
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       DOTNET_NOLOGO = 1
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       DOTNET_ROOT = /home/runner/.dotnet
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       DOTNET_ROOT_X64 = /home/runner/.dotnet
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       DOTNET_SKIP_FIRST_TIME_EXPERIENCE = 1
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       DOTNET_STARTUP_HOOKS = /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/bin/tracer-home/netcoreapp3.1/OpenTelemetry.AutoInstrumentation.StartupHook.dll
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       OTEL_DOTNET_AUTO_ADDITIONAL_SOURCES = Samples.*
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       OTEL_DOTNET_AUTO_DEBUG = 1
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       OTEL_DOTNET_AUTO_HOME = /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/bin/tracer-home
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       OTEL_DOTNET_AUTO_INCLUDE_PROCESSES = dotnet
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       OTEL_DOTNET_AUTO_INTEGRATIONS_FILE = /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/bin/tracer-home/integrations.json
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       OTEL_DOTNET_AUTO_LOG_DIRECTORY = /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/build_data/profiler-logs
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       OTEL_EXPORTER_ZIPKIN_ENDPOINT = http://127.0.0.1:34845/
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       OTEL_SERVICE_NAME = Samples.GraphQL
  17:18:55 [DBG]  [webserver][stdout] \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Samples.GraphQL.Program[0]
  17:18:55 [DBG]  [webserver][stdout]       OTEL_TRACES_EXPORTER = zipkin
  17:18:55 [DBG]  [webserver][stdout] \x1b[41m\x1b[1m\x1b[37mcrit\x1b[39m\x1b[22m\x1b[49m: Microsoft.AspNetCore.Server.Kestrel[0]
  17:18:55 [DBG]  [webserver][stdout]       Unable to start Kestrel.
  17:18:55 [DBG]  [webserver][stdout] System.IO.IOException: Failed to bind to address [http://127.0.0.1:37149:](http://127.0.0.1:37149/) address already in use.
  17:18:55 [DBG]  [webserver][stdout]  ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
  17:18:55 [DBG]  [webserver][stdout]  ---> System.Net.Sockets.SocketException (98): Address already in use
  17:18:55 [DBG]  [webserver][stdout]    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
  17:18:55 [DBG]  [webserver][stdout]    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
  17:18:55 [DBG]  [webserver][stdout]    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
  17:18:55 [DBG]  [webserver][stdout]    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
  17:18:55 [DBG]  [webserver][stdout]    --- End of inner exception stack trace ---
  17:18:55 [DBG]  [webserver][stdout]    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
  17:18:55 [DBG]  [webserver][stdout]    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
  17:18:55 [DBG]  [webserver][stderr] Unhandled exception. System.IO.IOException: Failed to bind to address [http://127.0.0.1:37149:](http://127.0.0.1:37149/) address already in use.
  17:18:55 [DBG]  [webserver][stderr]  ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
  17:18:55 [DBG]  [webserver][stderr]  ---> System.Net.Sockets.SocketException (98): Address already in use
  17:18:55 [DBG]  [webserver][stderr]    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
  17:18:55 [DBG]  [webserver][stderr]    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
  17:18:55 [DBG]  [webserver][stderr]    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
  17:18:55 [DBG]  [webserver][stderr]    --- End of inner exception stack trace ---
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
  17:18:55 [DBG]  [webserver][stderr] --- End of stack trace from previous location where exception was thrown ---
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
  17:18:55 [DBG]  [webserver][stderr]    --- End of inner exception stack trace ---
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
  17:18:55 [DBG]  [webserver][stderr]    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
  17:18:55 [DBG]  [webserver][stderr]    at Samples.GraphQL.Program.Main(String[] args) in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/test-applications/integrations/Samples.GraphQL/Program.cs:line 61
  17:18:55 [DBG]  [webserver][stdout]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
  17:18:55 [DBG]  [webserver][stdout] --- End of stack trace from previous location where exception was thrown ---
  17:18:55 [DBG]  [webserver][stdout]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
  17:18:55 [DBG]  [webserver][stdout]    --- End of inner exception stack trace ---
  17:18:55 [DBG]  [webserver][stdout]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
  17:18:55 [DBG]  [webserver][stdout]    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
  17:18:55 [DBG]  [webserver][stdout]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
  17:18:55 [DBG]  [webserver][stdout]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
  17:18:55 [DBG]  [webserver][stdout]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
  17:18:55 [DBG]  [webserver][stdout] >>>>>>>>>>>>>>>>>>>>>>> Process: dotnet(3788): UnhandledException event raised with a terminating exception.
  17:18:55 [DBG]  [webserver][stdout] >>>>>>>>>>>>>>>>>>>>>>> Process: dotnet(3788): OpenTelemetry tracer exit.
  17:18:55 [DBG]  The server is ready.
  17:18:55 [DBG]  [http] OK {}
  17:18:55 [DBG]  [http] exception: System.Net.WebException: An error occurred while sending the request. The response ended prematurely.
  17:18:55 [DBG]   ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
  17:18:55 [DBG]   ---> System.IO.IOException: The response ended prematurely.
  17:18:55 [DBG]     at System.Net.Http.HttpConnection.FillAsync()
  17:18:55 [DBG]     at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
  17:18:55 [DBG]     at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     --- End of inner exception stack trace ---
  17:18:55 [DBG]     at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
  17:18:55 [DBG]     at System.Net.HttpWebRequest.SendRequest()
  17:18:55 [DBG]     at System.Net.HttpWebRequest.GetResponse()
  17:18:55 [DBG]     --- End of inner exception stack trace ---
  17:18:55 [DBG]     at System.Net.HttpWebRequest.GetResponse()
  17:18:55 [DBG]     at IntegrationTests.GraphQL.GraphQLTests.SubmitRequest(Int32 aspNetCorePort, RequestInfo requestInfo, Boolean printResponseText) in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/integration-tests/IntegrationTests.GraphQL/GraphQLTests.cs:line 258
  17:18:55 [DBG]  [http] exception: System.Net.WebException: Connection refused Connection refused
  17:18:55 [DBG]   ---> System.Net.Http.HttpRequestException: Connection refused
  17:18:55 [DBG]   ---> System.Net.Sockets.SocketException (111): Connection refused
  17:18:55 [DBG]     at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
  17:18:55 [DBG]     --- End of inner exception stack trace ---
  17:18:55 [DBG]     at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
  17:18:55 [DBG]     at System.Net.HttpWebRequest.SendRequest()
  17:18:55 [DBG]     at System.Net.HttpWebRequest.GetResponse()
  17:18:55 [DBG]     --- End of inner exception stack trace ---
  17:18:55 [DBG]     at System.Net.HttpWebRequest.GetResponse()
  17:18:55 [DBG]     at IntegrationTests.GraphQL.GraphQLTests.SubmitRequest(Int32 aspNetCorePort, RequestInfo requestInfo, Boolean printResponseText) in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/integration-tests/IntegrationTests.GraphQL/GraphQLTests.cs:line 258
  17:18:55 [DBG]  [http] exception: System.Net.WebException: Connection refused Connection refused
  17:18:55 [DBG]   ---> System.Net.Http.HttpRequestException: Connection refused
  17:18:55 [DBG]   ---> System.Net.Sockets.SocketException (111): Connection refused
  17:18:55 [DBG]     at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
  17:18:55 [DBG]     --- End of inner exception stack trace ---
  17:18:55 [DBG]     at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
  17:18:55 [DBG]     at System.Net.HttpWebRequest.SendRequest()
  17:18:55 [DBG]     at System.Net.HttpWebRequest.GetResponse()
  17:18:55 [DBG]     --- End of inner exception stack trace ---
  17:18:55 [DBG]     at System.Net.HttpWebRequest.GetResponse()
  17:18:55 [DBG]     at IntegrationTests.GraphQL.GraphQLTests.SubmitRequest(Int32 aspNetCorePort, RequestInfo requestInfo, Boolean printResponseText) in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/integration-tests/IntegrationTests.GraphQL/GraphQLTests.cs:line 258
  17:18:55 [DBG]  [http] exception: System.Net.WebException: Connection refused Connection refused
  17:18:55 [DBG]   ---> System.Net.Http.HttpRequestException: Connection refused
  17:18:55 [DBG]   ---> System.Net.Sockets.SocketException (111): Connection refused
  17:18:55 [DBG]     at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
  17:18:55 [DBG]     --- End of inner exception stack trace ---
  17:18:55 [DBG]     at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
  17:18:55 [DBG]     at System.Net.HttpWebRequest.SendRequest()
  17:18:55 [DBG]     at System.Net.HttpWebRequest.GetResponse()
  17:18:55 [DBG]     --- End of inner exception stack trace ---
  17:18:55 [DBG]     at System.Net.HttpWebRequest.GetResponse()
  17:18:55 [DBG]     at IntegrationTests.GraphQL.GraphQLTests.SubmitRequest(Int32 aspNetCorePort, RequestInfo requestInfo, Boolean printResponseText) in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/integration-tests/IntegrationTests.GraphQL/GraphQLTests.cs:line 258
  17:18:55 [DBG]  [http] exception: System.Net.WebException: Connection refused Connection refused
  17:18:55 [DBG]   ---> System.Net.Http.HttpRequestException: Connection refused
  17:18:55 [DBG]   ---> System.Net.Sockets.SocketException (111): Connection refused
  17:18:55 [DBG]     at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
  17:18:55 [DBG]     --- End of inner exception stack trace ---
  17:18:55 [DBG]     at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  17:18:55 [DBG]     at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
  17:18:55 [DBG]     at System.Net.HttpWebRequest.SendRequest()
  17:18:55 [DBG]     at System.Net.HttpWebRequest.GetResponse()
  17:18:55 [DBG]     --- End of inner exception stack trace ---
  17:18:55 [DBG]     at System.Net.HttpWebRequest.GetResponse()
  17:18:55 [DBG]     at IntegrationTests.GraphQL.GraphQLTests.SubmitRequest(Int32 aspNetCorePort, RequestInfo requestInfo, Boolean printResponseText) in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/integration-tests/IntegrationTests.GraphQL/GraphQLTests.cs:line 258
  17:18:55 [DBG]  [MockZipkinCollector]: Shutting down. Total spans received: '0'
  17:18:55 [DBG] 
  17:18:55 [DBG] 
  17:18:55 [DBG] Results File: /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/build_data/results/IntegrationTests.GraphQL/_fv-az213-608_[2022](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/5724511365?check_suite_focus=true#step:5:2022)-03-28_17_18_55.trx
  17:18:55 [DBG] 
  17:18:55 [DBG] Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/test/integration-tests/IntegrationTests.GraphQL/bin/x64/Release/netcoreapp3.1/IntegrationTests.GraphQL.dll (netcoreapp3.1)
```

**Comment by pjanotti** [comment]
Same test but now it captured some spans so it can't simply be (at least in this instance) only the port issue https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/runs/5746098445?check_suite_focus=true#step:5:3008

**Comment by pellared** [comment]
I will look at this one at least for a week but I have not spotted failing it recently.

**Comment by pellared** [comment]
I have not seen this test failing for a few weeks. Closing.
