### ISSUE TITLE
Flaky test: RuntimeMetrics.RuntimeMetricsWriterTests.ShouldCaptureFirstChanceExceptions

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-dotnet-instrumentation#67]
The test is falling many times in CI:

```
2021-03-03T20:24:39.5684852Z [xUnit.net 00:00:11.3384586]     Datadog.Trace.Tests.RuntimeMetrics.RuntimeMetricsWriterTests.ShouldCaptureFirstChanceExceptions [FAIL]
2021-03-03T20:24:40.9605968Z   Failed Datadog.Trace.Tests.RuntimeMetrics.RuntimeMetricsWriterTests.ShouldCaptureFirstChanceExceptions [46 ms]
2021-03-03T20:24:40.9607521Z   Error Message:
2021-03-03T20:24:40.9608473Z    Moq.MockException : 
2021-03-03T20:24:40.9609815Z Expected invocation on the mock should never have been performed, but was 2 times: s => s.Increment("runtime.dotnet.exceptions.count", It.IsAny<Int32>(), It.IsAny<Double>(), It.IsAny<String[]>())
2021-03-03T20:24:40.9611297Z No setups configured.
2021-03-03T20:24:40.9612154Z 
2021-03-03T20:24:40.9612520Z Performed invocations: 
2021-03-03T20:24:40.9613149Z IDogStatsd.Gauge("runtime.dotnet.threads.count", 40, 1, null)
2021-03-03T20:24:40.9613627Z IDogStatsd.Gauge("runtime.dotnet.mem.committed", 202768384, 1, null)
2021-03-03T20:24:40.9614132Z IDogStatsd.Gauge("runtime.dotnet.cpu.user", -15625, 1, null)
2021-03-03T20:24:40.9614616Z IDogStatsd.Gauge("runtime.dotnet.cpu.system", 0, 1, null)
2021-03-03T20:24:40.9615154Z IDogStatsd.Gauge("runtime.dotnet.cpu.percent", -390.6, 1, null)
2021-03-03T20:24:40.9615866Z IDogStatsd.Increment("runtime.dotnet.exceptions.count", 1, 1, ["exception_type:SocketException"])
2021-03-03T20:24:40.9616628Z IDogStatsd.Increment("runtime.dotnet.exceptions.count", 5, 1, ["exception_type:WebException"])
2021-03-03T20:24:40.9617276Z   Stack Trace:
2021-03-03T20:24:40.9617972Z      at Moq.Mock.ThrowVerifyException(MethodCall expected, IEnumerable`1 setups, IEnumerable`1 actualCalls, Expression expression, Times times, Int32 callCount)
2021-03-03T20:24:40.9618830Z    at Moq.Mock.VerifyCalls(Mock targetMock, MethodCall expected, Expression expression, Times times)
2021-03-03T20:24:40.9619554Z    at Moq.Mock.Verify[T](Mock`1 mock, Expression`1 expression, Times times, String failMessage)
2021-03-03T20:24:40.9620174Z    at Moq.Mock`1.Verify(Expression`1 expression, Times times)
2021-03-03T20:24:40.9620789Z    at Moq.Mock`1.Verify(Expression`1 expression, Func`1 times)
2021-03-03T20:24:40.9622069Z    at Datadog.Trace.Tests.RuntimeMetrics.RuntimeMetricsWriterTests.ShouldCaptureFirstChanceExceptions() in D:\a\1\s\test\Datadog.Trace.Tests\RuntimeMetrics\RuntimeMetricsWriterTests.cs:line 90
2021-03-03T20:24:43.6757048Z Results File: D:\a\_temp\VssAdministrator_WIN-4TJ496I205J_2021-03-03_20_24_30.trx
2021-03-03T20:24:43.6758094Z 
2021-03-03T20:24:43.6811170Z Failed!  - Failed:     1, Passed:   396, Skipped:     1, Total:   398, Duration: 30 s - Datadog.Trace.Tests.dll (net461)

2021-03-02T19:18:55.1876354Z [xUnit.net 00:00:10.4189318]     Datadog.Trace.Tests.RuntimeMetrics.RuntimeMetricsWriterTests.ShouldCaptureFirstChanceExceptions [FAIL]
2021-03-02T19:18:55.2040127Z   Failed Datadog.Trace.Tests.RuntimeMetrics.RuntimeMetricsWriterTests.ShouldCaptureFirstChanceExceptions [54 ms]
2021-03-02T19:18:55.2042995Z   Error Message:
2021-03-02T19:18:55.2045234Z    Moq.MockException : 
2021-03-02T19:18:55.2046916Z Expected invocation on the mock should never have been performed, but was 3 times: s => s.Increment("runtime.dotnet.exceptions.count", It.IsAny<Int32>(), It.IsAny<Double>(), It.IsAny<String[]>())
2021-03-02T19:18:55.2050639Z No setups configured.
2021-03-02T19:18:55.2052439Z 
2021-03-02T19:18:55.2053635Z Performed invocations: 
2021-03-02T19:18:55.2055103Z IDogStatsd.Gauge("runtime.dotnet.threads.count", 32, 1, null)
2021-03-02T19:18:55.2056424Z IDogStatsd.Gauge("runtime.dotnet.mem.committed", 373817344, 1, null)
2021-03-02T19:18:55.2057526Z IDogStatsd.Gauge("runtime.dotnet.cpu.user", -15625, 1, null)
2021-03-02T19:18:55.2058760Z IDogStatsd.Gauge("runtime.dotnet.cpu.system", 0, 1, null)
2021-03-02T19:18:55.2059793Z IDogStatsd.Gauge("runtime.dotnet.cpu.percent", -390.6, 1, null)
2021-03-02T19:18:55.2061088Z IDogStatsd.Increment("runtime.dotnet.exceptions.count", 10, 1, ["exception_type:WebException"])
2021-03-02T19:18:55.2062359Z IDogStatsd.Increment("runtime.dotnet.exceptions.count", 2, 1, ["exception_type:SocketException"])
2021-03-02T19:18:55.2064122Z IDogStatsd.Increment("runtime.dotnet.exceptions.count", 20, 1, ["exception_type:HttpRequestException"])
2021-03-02T19:18:55.2080657Z   Stack Trace:
2021-03-02T19:18:55.2082925Z      at Moq.Mock.ThrowVerifyException(MethodCall expected, IEnumerable`1 setups, IEnumerable`1 actualCalls, Expression expression, Times times, Int32 callCount) in C:\projects\moq4\Source\Mock.cs:line 473
2021-03-02T19:18:55.2085217Z    at Moq.Mock.VerifyCalls(Mock targetMock, MethodCall expected, Expression expression, Times times) in C:\projects\moq4\Source\Mock.cs:line 451
2021-03-02T19:18:55.2086761Z    at Moq.Mock.Verify[T](Mock`1 mock, Expression`1 expression, Times times, String failMessage) in C:\projects\moq4\Source\Mock.cs:line 314
2021-03-02T19:18:55.2089574Z    at Moq.Mock`1.Verify(Expression`1 expression, Times times) in C:\projects\moq4\Source\Mock.Generic.cs:line 459
2021-03-02T19:18:55.2090985Z    at Moq.Mock`1.Verify(Expression`1 expression, Func`1 times) in C:\projects\moq4\Source\Mock.Generic.cs:line 466
2021-03-02T19:18:55.2092622Z    at Datadog.Trace.Tests.RuntimeMetrics.RuntimeMetricsWriterTests.ShouldCaptureFirstChanceExceptions() in D:\a\1\s\test\Datadog.Trace.Tests\RuntimeMetrics\RuntimeMetricsWriterTests.cs:line 90
2021-03-02T19:18:56.4223223Z Results File: D:\a\_temp\VssAdministrator_WIN-80S6H5TTEN9_2021-03-02_19_18_47.trx
2021-03-02T19:18:56.4224315Z 
2021-03-02T19:18:56.4325403Z Failed!  - Failed:     1, Passed:   396, Skipped:     1, Total:   398, Duration: 35 s - Datadog.Trace.Tests.dll (netcoreapp2.1)

2021-03-03T00:57:08.9749625Z [xUnit.net 00:00:10.0116210]     Datadog.Trace.Tests.RuntimeMetrics.RuntimeMetricsWriterTests.ShouldCaptureFirstChanceExceptions [FAIL]
2021-03-03T00:57:09.1419253Z   Failed Datadog.Trace.Tests.RuntimeMetrics.RuntimeMetricsWriterTests.ShouldCaptureFirstChanceExceptions [22 ms]
2021-03-03T00:57:09.1428692Z   Error Message:
2021-03-03T00:57:09.1453711Z    Moq.MockException : 
2021-03-03T00:57:09.1455001Z Expected invocation on the mock should never have been performed, but was 2 times: s => s.Increment("runtime.dotnet.exceptions.count", It.IsAny<Int32>(), It.IsAny<Double>(), It.IsAny<String[]>())
2021-03-03T00:57:09.1456383Z No setups configured.
2021-03-03T00:57:09.1457056Z 
2021-03-03T00:57:09.1457807Z Performed invocations: 
2021-03-03T00:57:09.1458712Z IDogStatsd.Gauge("runtime.dotnet.threads.count", 31, 1, null)
2021-03-03T00:57:09.1460517Z IDogStatsd.Gauge("runtime.dotnet.mem.committed", 284004352, 1, null)
2021-03-03T00:57:09.1461531Z IDogStatsd.Gauge("runtime.dotnet.cpu.user", -0, 1, null)
2021-03-03T00:57:09.1462586Z IDogStatsd.Gauge("runtime.dotnet.cpu.system", -0, 1, null)
2021-03-03T00:57:09.1463482Z IDogStatsd.Gauge("runtime.dotnet.cpu.percent", -0, 1, null)
2021-03-03T00:57:09.1464559Z IDogStatsd.Increment("runtime.dotnet.exceptions.count", 31, 1, ["exception_type:HttpRequestException"])
2021-03-03T00:57:09.1465895Z IDogStatsd.Increment("runtime.dotnet.exceptions.count", 12, 1, ["exception_type:SocketException"])
2021-03-03T00:57:09.1466851Z   Stack Trace:
2021-03-03T00:57:09.1467885Z      at Moq.Mock.ThrowVerifyException(MethodCall expected, IEnumerable`1 setups, IEnumerable`1 actualCalls, Expression expression, Times times, Int32 callCount)
2021-03-03T00:57:09.1469998Z    at Moq.Mock.VerifyCalls(Mock targetMock, MethodCall expected, Expression expression, Times times)
2021-03-03T00:57:09.1471134Z    at Moq.Mock.Verify[T](Mock`1 mock, Expression`1 expression, Times times, String failMessage)
2021-03-03T00:57:09.1472169Z    at Moq.Mock`1.Verify(Expression`1 expression, Times times)
2021-03-03T00:57:09.1473214Z    at Moq.Mock`1.Verify(Expression`1 expression, Func`1 times)
2021-03-03T00:57:09.1477637Z    at Datadog.Trace.Tests.RuntimeMetrics.RuntimeMetricsWriterTests.ShouldCaptureFirstChanceExceptions() in D:\a\1\s\test\Datadog.Trace.Tests\RuntimeMetrics\RuntimeMetricsWriterTests.cs:line 90
2021-03-03T00:57:09.2229895Z Results File: D:\a\_temp\VssAdministrator_fv-az91-343_2021-03-03_00_57_00.trx
2021-03-03T00:57:09.2231262Z 
2021-03-03T00:57:09.2276522Z Failed!  - Failed:     1, Passed:   399, Skipped:     1, Total:   401, Duration: 32 s - Datadog.Trace.Tests.dll (net5.0)
```

**Comment by zacharycmontoya** [comment]
We are seeing this same test failing in the DataDog/dd-trace-dotnet repo as well. We are tracking this flaky test so it is on our radar to be investigated. In the meantime, feel free to disable this test in CI so it doesn't create additional noise.

**Comment by zacharycmontoya** [comment]
Attempted test fix at https://github.com/DataDog/dd-trace-dotnet/pull/1263

**Comment by pellared** [comment]
@zacharycmontoya @pjanotti I think this can be closed.

**Comment by zacharycmontoya** [comment]
Yes you're correct, this was pulled in this upstream PR: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/89
