### ISSUE TITLE
undefined symbol: pthread_cond_clockwait while deploy OpenTelemetry with dotnet/aspnet:5.0 AS base

### ISSUE THREAD

**Issue by herskovi** [open-telemetry/opentelemetry-dotnet-instrumentation#703]
Hi,

While trying to Instrument a .NET application with docker image based on dotnet/aspnet:5.0 AS base, kubernetes crushed with below. 
 
**dotnet: symbol lookup error: /app/otelInstrumentaion/OpenTelemetry.AutoInstrumentation.Native.so: undefined symbol: pthread_cond_clockwait**

Docker Image was built on Ubuntu with dotnet/aspnet5:0 AS base. 
After upgrade from dotnet/aspnet:5.0 to dotnet/aspnet:5.0-focal AS base I'm getting the following error:

Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'OpenTelemetry.AutoInstrumentation.Loader.Startup' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'OpenTelemetry.Sdk' threw an exception.
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
File name: 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String assemblyPath, String nativeImagePath)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)
   --- End of inner exception stack trace ---
   at OpenTelemetry.Sdk.CreateTracerProviderBuilder()
   at OpenTelemetry.AutoInstrumentation.Instrumentation.Initialize() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs:line 86
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OpenTelemetry.AutoInstrumentation.Loader.Startup.TryLoadManagedAssembly() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation.Loader/Startup.cs:line 71
   at OpenTelemetry.AutoInstrumentation.Loader.Startup..cctor() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation.Loader/Startup.cs:line 45
   --- End of inner exception stack trace ---
   at OpenTelemetry.AutoInstrumentation.Loader.Startup..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Reflection.Assembly.CreateInstance(String typeName)
   at StartupHook.Initialize() in /home/runner/work/opentelemetry-dotnet-instrumentation/opentelemetry-dotnet-instrumentation/src/OpenTelemetry.AutoInstrumentation.StartupHook/StartupHook.cs:line 57
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath startupHook)
   at System.StartupHookProvider.ProcessStartupHooks()

Can someone advise if dotnet/aspnet:5.0 is supported?

**Comment by Kielek** [comment]
@herskovi,
if you are using https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/tag/v0.1.0-beta.1 the .NET 5.0 is supported, but this support will be dropped in the upcoming beta release. Please check https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/6e31d56b640e85da0d604943819711afd2ef9d7e/CHANGELOG.md?plain=1#L37-L39

What is more, .NET 5. is out of support since May 10th. For details, please check  https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/

The minimal version supported version of `System.Diagnostics.DiagnosticSource` is 6.0. .NET 5 by 
default ships version 5.0. 

I see two solution you can follow

* (recommended) if it is possible, upgrade your solution to .NET 6. It is LTS version. Correct `DiagnosticSource` should be loaded automatically.
* add [`System.Diagnostics.DiagnosticSource` v 6.0](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/6.0.0 ) reference to your project. It should bring correct version to the runtime. As a reference you can check this comment https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/647#issuecomment-1117269528. There were a similar issue related to the .NET Core 3.1.

**Comment by pjanotti** [comment]
This looks like some dependency on the pthread library that is not present on the docker dotnet 5.0 docker image. I can't repro it with the net6.0 sdk image so as suggested above this likely is fixed on net 6.0.

**Comment by pjanotti** [comment]
So the first error `symbol lookup error: /opt/opentelemetry-dotnet-autoinstrumentation/OpenTelemetry.AutoInstrumentation.Native.so: undefined symbol: pthread_cond_clockwait` is really related to the libraries required by the native component. Similar to what @herskovi reported I got the error above when attempting to use auto instrumentation with the `mcr.microsoft.com/dotnet/sdk:3.1` image, if I switch to `mcr.microsoft.com/dotnet/sdk:3.1-bullseye` the error is gone.

For the second error adding the package as suggested by @Kielek should suffice.

**Comment by Kielek** [comment]
@herskovi, did you have a chance to apply our suggestions? Does it help?

**Comment by pjanotti** [comment]
We have a report of the native error on slack: https://cloud-native.slack.com/archives/C01N3BC2W7Q/p1667586856575079

For now keeping this issue closed until we have more context.

**Comment by pellared** [comment]
I suspect there is an "old" version of `glibc`

I see that `pthread_cond_clockwait` was introduced in version 2.30. Reference: https://lwn.net/Articles/795127/
