### ISSUE TITLE
Instrumenting OTEL with .net core Application on IIS 

### ISSUE THREAD

**Issue by NamitaJaokar** [open-telemetry/opentelemetry-dotnet-instrumentation#704]
Hi Team,

I have hosted my net core application on IIS and trying to capture the traces with the latest beta release version of OTEL and zipkin exporter.
After Performing transactions in my application, I am unable to view the traces.
On checking the logs for the same , Came across below error :
[2022-05-30T13:36:40.2539228Z] [Error] EventSource=OpenTelemetry-Exporter-Zipkin, Message=Failed to export activities: 'System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at OpenTelemetry.Exporter.ZipkinExporter.Export(Batch`1& batch)' 

The zipkin dashboard has below error while trying to find the traces:
![image](https://user-images.githubusercontent.com/32196871/171008735-bb8aee3b-9fcd-4bb6-a335-17d7b7faa86e.png)

I have Environment variables added in my system
COR_ENABLE_PROFILING=1
COR_PROFILER={918728DD-259F-4A6A-AC2B-B85E1B658318}
COR_PROFILER_PATH_64=D:/OTEL-dotnet/opentelemetry-dotnet-instrumentation-windows/win-x64/OpenTelemetry.AutoInstrumentation.Native.dll
CORECLR_ENABLE_PROFILING=1
CORECLR_PROFILER={918728DD-259F-4A6A-AC2B-B85E1B658318}
CORECLR_PROFILER_PATH_64=D:/OTEL-dotnet/opentelemetry-dotnet-instrumentation-windows/win-x64/OpenTelemetry.AutoInstrumentation.Native.dll
DOTNET_ADDITIONAL_DEPS=D:/OTEL-dotnet/opentelemetry-dotnet-instrumentation-windows/AdditionalDeps
DOTNET_SHARED_STORE=D:/OTEL-dotnet/opentelemetry-dotnet-instrumentation-windows/store
DOTNET_STARTUP_HOOKS=D:/OTEL-dotnet/opentelemetry-dotnet-instrumentation-windows/netcoreapp3.1/OpenTelemetry.AutoInstrumentation.StartupHook.dll
OTEL_DOTNET_AUTO_DEBUG=1
OTEL_DOTNET_AUTO_ENABLED=1
OTEL_DOTNET_AUTO_ENABLED_INSTRUMENTATIONS=AspNet
OTEL_DOTNET_AUTO_INCLUDE_PROCESSES=EmpApplication.exe
OTEL_DOTNET_AUTO_INTEGRATIONS_FILE=D:/OTEL-dotnet/opentelemetry-dotnet-instrumentation-windows/integrations.json
OTEL_DOTNET_AUTO_LOG_DIRECTORY=C:/ProgramData/OpenTelemetry .NET AutoInstrumentation/logs
OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://localhost:9411/api/v2/spans
OTEL_TRACES_EXPORTER=zipkin
OTEL_SERVICE_NAME=ServiceName
OTEL_TRACES_EXPORTER=zipkin

Could you please advise as to what might be causing this error or anything that is required and I might have missed it from the configurations.

Thank you in advance!
Best Regards,
Namita Jaokar

**Comment by nrcventura** [comment]
Based on those troubleshooting logs, it looks like the zipkin exporter is unable to establish a connection to your local zipkin instance. You should attempt to see if you can ping/curl that zipkin endpoint from the machine that your application is running on. Is zipkin configured to receive data on that port on that machine? If zipkin is running in a container, you'll need to ensure that the correct ports are enabled for that instance.

**Comment by Kielek** [comment]
@NamitaJaokar, did you have chance to look into the issue once more time?

**Comment by NamitaJaokar** [comment]
Hi @Kielek , I was able to connect with zipkin server and the services were also visible to me. Did not do anything to get it fixed but after multiple system restart, It did work for me. Intermittent connection to zipkin server is what I have observed.

Best Regards,
Namita

**Comment by pellared** [comment]
@NamitaJaokar Is there anything left or can we close this issue?

**Comment by NamitaJaokar** [comment]
@pellared  yes, Can be closed

Thanks & Regards,
Namita
